Grt: add debug mode
The-OpenROAD-Project/OpenROAD pull request #1104
Opened 2021-09-16 18:13 UTC by luis201420

2021-09-16 19:13 UTC, maliberty requested changes

2021-09-16 19:13 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +    painter.setPenWidth(700);
hoist out of the loop

2021-09-16 19:13 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +  if (treeStructure_ == 1) {
Can an enum be used rather than 1 & 2?

2021-09-16 19:13 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +}
I only see a caller in the ctor so you might as well just move this one line there.

2021-09-16 19:13 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +      fastrouteRender_->highlight(net);
does this belong in the initialization?  What happens on a second call to this method?

2021-09-16 19:13 UTC, maliberty commented on src/grt/src/fastroute/src/RSMT.cpp
> +    if (debug_->isOn_ && debug_->steinerTree_ && net->db_net->getName() == const_cast<odb::dbNet*>(debug_->net_)->getName()) {
compare pointers not names

2021-09-16 21:49 UTC, maliberty requested changes

2021-09-16 21:49 UTC, maliberty commented on src/grt/src/GlobalRouter.tcl
> +    grt::set_global_route_debug_cmd [$db_block findNet $keys(-net)] $st $rst $tree2D $tree3D
You should have some error handling in case the net isn't found.

2021-09-16 21:49 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +      treeStructure_;  // 1 Steiner Tree By stt, 2 Steiner Tree by Fastroute
Move the comments to the enum and drop the 1&2

2021-09-16 22:28 UTC, vvbandeira commented
I think the command, options, usage (maybe an example image?) should be documented in `src/grt/README.md`.

2021-09-16 23:40 UTC, maliberty commented
@vvbandeira this is mostly intended for developer use though I suppose anyone could use it who is interested.

2021-09-17 00:45 UTC, vvbandeira commented
> @vvbandeira this is mostly intended for developer use though I suppose anyone could use it who is interested.

@maliberty I understand that the target user is a developer. Maybe full documentation and description might be over the top, but I think we should at least mention somewhere that such debug feature exists.

2021-09-17 01:34 UTC, maliberty commented
> > @vvbandeira this is mostly intended for developer use though I suppose anyone could use it who is interested.
> 
> @maliberty I understand that the target user is a developer. Maybe full documentation and description might be over the top, but I think we should at least mention somewhere that such debug feature exists.

Sure

2021-09-17 18:47 UTC, eder-matheus commented
> > @vvbandeira this is mostly intended for developer use though I suppose anyone could use it who is interested.
> 
> @maliberty I understand that the target user is a developer. Maybe full documentation and description might be over the top, but I think we should at least mention somewhere that such debug feature exists.

@vvbandeira Could you look at the description added by Luis?

2021-09-21 18:42 UTC, maliberty requested changes

2021-09-21 18:42 UTC, maliberty commented on src/grt/src/fastroute/src/FastRoute.cpp
> +  steinerTreeByFastroute  // Steiner Tree by Fastroute
actually the comments seem redundant now that we have enums with good names

2021-09-21 19:54 UTC, maliberty approved these changes

2021-09-22 16:40 UTC, merged