Make it possible for p/g pins to place at all sides
The-OpenROAD-Project/OpenROAD pull request #1190
Opened 2021-10-12 07:53 UTC by TimeExceed

Besides that,

1. circuits connecting core rings and p/g pins go a little bit deeper into p/g pins to improve connectivity.
2. p/g pins are connected to core rings at all layers.

Signed-off-by: TimeExceed <tyf00@aliyun.com>

2021-11-01 22:16 UTC, QuantamHD commented
@TimeExceed Unfortunately I'm just a community member so I can't sign off on your PR. @Colin-Holehouse do you know when you would be able to give this a once over?

2021-11-29 17:15 UTC, maliberty commented
@Colin-Holehouse please review

2022-02-14 15:26 UTC, maliberty commented
@arlpetergadfort anything to incorporate here for your version?

2022-02-14 15:58 UTC, arlpetergadfort commented
> @arlpetergadfort anything to incorporate here for your version?

I think this is covered by `-connect_to_pads` in the `add_pdn _ring` command, it will ensure all the iterms facing the core are connected (if possible and connected to the ring nets in the database) to the ring on all layers with connect assignments.

2022-02-21 13:05 UTC, Colin-Holehouse commented on src/pdn/test/four_sides/pad.lef
> +        RECT 3.28 77.9 50.735 80 ;
This pin shape overlaps all the previously defined pin shapes in the same layer. Seems like the smaller pin shapes should be removed.

2022-02-21 13:07 UTC, Colin-Holehouse commented on src/pdn/test/four_sides/pdn.cfg
> +}
Its a strange design that has no rails or straps. The straps do interact with the connections to the core rings, so whouls probably be included.

2022-02-21 13:14 UTC, Colin-Holehouse commented on src/pdn/src/PdnGen.tcl
> -
This code specifically checks that in order to connect two layers together, that there is a full overlap of the lines. A parial overlap can result in problems with via sizing, and are likely the result of a poor floorplan, or interaction of macros cutting channels into the design.
I believe this code needs to be retained.

2022-02-21 13:21 UTC, Colin-Holehouse commented on src/pdn/src/PdnGen.tcl
> +}
If there is no MAXWIDTH rule defined for the layer, then the width of the pin should be used.

2022-02-21 13:35 UTC, Colin-Holehouse requested changes
It's not very clear what this change is trying to achieve.

The testcase seems somewhat contrived, consisting of just pads and stdcell rows, and the LEF descriptions provided seem to define overlapping pins, which is likely to be problematic.

Some unrelated changes have been done, to cope with the fact that the testcase has no straps defined (unrealistic setup, but the changes are benign), and some code to check layer overlap sizes has been removed that I believe is a core part of how pdn works.

Best I can make out, the code is primarily looking to cope with wide p/g pins on the pads as they connect to the core rings, and tries to automate the addition of a number of max width straps from the pad pin to the core ring when the pin on the pad is very wide.

Its not clear to me that the suggested approach here is always the one that is desired, but there are no alternative approaches allowed (e.g. the current approach could still be appropriate).

2022-03-24 07:22 UTC, TimeExceed commented
> It's not very clear what this change is trying to achieve.
> 
> The testcase seems somewhat contrived, consisting of just pads and stdcell rows, and the LEF descriptions provided seem to define overlapping pins, which is likely to be problematic.
> 
> Some unrelated changes have been done, to cope with the fact that the testcase has no straps defined (unrealistic setup, but the changes are benign), and some code to check layer overlap sizes has been removed that I believe is a core part of how pdn works.
> 
> Best I can make out, the code is primarily looking to cope with wide p/g pins on the pads as they connect to the core rings, and tries to automate the addition of a number of max width straps from the pad pin to the core ring when the pin on the pad is very wide.
> 
> Its not clear to me that the suggested approach here is always the one that is desired, but there are no alternative approaches allowed (e.g. the current approach could still be appropriate).

You are right. It is not very clear. I shall split this pr into several ones.

Thank u very much.

2022-03-24 07:22 UTC, closed without merging