grt: Algorithm should not change with execution time
The-OpenROAD-Project/OpenROAD pull request #1513
Opened 2022-01-05 10:10 UTC by antonblanchard

Remove some strange code which measures the time taken to execute a
chunk of code, and then makes decisions based on that.

Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

2022-01-05 11:05 UTC, antonblanchard commented
A lot of the CI fails look like small differences in grt stats output, which is expected.

2022-01-05 16:23 UTC, eder-matheus commented
@antonblanchard I'll start a secure ci run with your updates before approving this PR. Meanwhile, could you update the ok files for the grt failing tests?

2022-01-05 18:50 UTC, maliberty commented
The changes look fine to me - I'll leave it to you and Eder to work out the CI issues and approve.

2022-01-05 20:10 UTC, antonblanchard commented
@eder-matheus Could do with some double checking. I had to manually do `save_guideok` for each test that mentioned differences in the test output, rerun the regression tests and finally `save_ok failures`. Makes me wonder if I am missing something.

2022-01-05 20:58 UTC, eder-matheus requested changes

2022-01-05 20:58 UTC, eder-matheus commented on src/grt/test/silence.ok
> +Differences found at line 642.
You missed only this `guideok`. Update this and the grt tests will be all correctly updated.

2022-01-05 21:25 UTC, eder-matheus commented
Thanks, @antonblanchard. The public CI is green, now I'm just waiting for the secure CI to end.

2022-01-06 16:33 UTC, eder-matheus approved these changes

2022-01-06 17:23 UTC, eder-matheus commented
@antonblanchard please update your branch with the latest master branch. We have two new grt tests that require updates in the ok files after your changes.

2022-01-06 22:25 UTC, antonblanchard commented
@eder-matheus updated to master

2022-01-06 23:02 UTC, merged