odb: support new lef58 mincut, widthtable, arrayspacing
The-OpenROAD-Project/OpenROAD pull request #1755
Opened 2022-04-06 16:02 UTC by osamahammad21

closes [OR-1391](https://openroad.atlassian.net/browse/OR-1391)

2022-04-07 04:13 UTC, maliberty commented on src/odb/src/db/dbModule.cpp
> -std::string dbModule::getHierarchicalName() const
Thanks for catching and fixing this.

2022-04-07 04:27 UTC, maliberty approved these changes

2022-04-07 04:27 UTC, maliberty commented on src/odb/src/db/dbTechLayerMinCutRule.h
> +// Copyright (c) 2020, The Regents of the University of California
Time to update the template year

2022-04-12 18:52 UTC, maliberty commented
You will need to update db_schema_initial & db_schema_minor in dbDatabase.h as we are now using .odb files and have to prevent cross loading across schema changes.

2022-04-12 18:53 UTC, maliberty requested changes
schema id

2022-04-13 13:52 UTC, osamahammad21 commented
> You will need to update db_schema_initial & db_schema_minor in dbDatabase.h as we are now using .odb files and have to prevent cross loading across schema changes.

@maliberty I am not familiar with those schema id. Can you explain what each one refers to?

2022-04-13 20:29 UTC, maliberty commented
They are the major/minor version numbers for the internal schema.  If you make a change the will result in a change to the .odb file you need to update the schema so that it can be detected.  The 'initial' schema seems to be for backwards compatibility where a version X schema could load a X-1 .odb by having conditional paths in the loading.  We aren't using that for now so simply updating them is enough to prevent version errors.

2022-04-13 21:47 UTC, maliberty approved these changes
@arlpetergadfort FYI

2022-04-17 18:01 UTC, merged