cts CharBuf selection is based on buffer with the max capacitance
The-OpenROAD-Project/OpenROAD pull request #1772
Opened 2022-04-12 13:29 UTC by habibayassin

Signed-off-by: habibayassin <habibayassin@aucegypt.edu>

2022-04-12 16:45 UTC, maliberty requested changes

2022-04-12 16:45 UTC, maliberty commented on src/cts/src/TechChar.cpp
> +      if( maxCap >= maxBuffCap){
You need to have !maxCapExists by using the library default as is done in the code further down.

2022-04-19 19:10 UTC, maliberty approved these changes

2022-04-19 21:00 UTC, maliberty approved these changes

2022-04-19 21:01 UTC, maliberty commented
I should have mentioned DCO to you.  When you commit you need to use '-s' to sign your commits.  I use a git alias for this so I don't forget.  Please click the Details link by DCO to get instructions on how to fix this up.

2022-04-21 00:02 UTC, habibayassin commented
I followed the instruction in the Details link by DCO. Is there anything else I should do?

2022-04-21 00:05 UTC, maliberty commented
Something seems to have gone quite wrong - you have a ton of conflicts in unrelated code.

2022-04-21 00:11 UTC, habibayassin commented
yes I have noticed, trying to solve the problem

2022-04-24 04:06 UTC, QuantamHD commented
@maliberty You need to kick off the scan workflow.

2022-04-25 15:07 UTC, merged