Odb group
The-OpenROAD-Project/OpenROAD pull request #1917
Opened 2022-05-26 18:14 UTC by osamahammad21

2022-05-26 19:43 UTC, maliberty commented on src/odb/src/db/dbRegion.cpp
> +    return;
clang-format

2022-05-26 19:43 UTC, maliberty commented on src/odb/src/db/dbRegion.cpp
> +  _group->region_next_ = _region->groups_;
You need to set the region_prev on the old head to the new group

2022-05-26 19:45 UTC, maliberty commented on src/odb/src/db/dbRegion.cpp
> +void dbRegion::removeGroup(dbGroup* group)
Verify that the group does belong to this region

2022-05-26 19:48 UTC, maliberty commented on src/ifp/src/InitFloorplan.cc
> +      dbRegion* domain_region = group->getRegion();
Ok for now as we only create single boxes but this will need to deal with rectilinear regions eventually.

2022-05-26 19:48 UTC, maliberty commented on src/odb/test/cpp/TestGroup.cpp
> +    domain = dbGroup::create(block,"domain");
Do we have tests for the group/region relationship?

2022-05-26 19:49 UTC, maliberty requested changes
Please update defin to map DEF GROUPS to dbGroups

2022-05-26 19:49 UTC, maliberty commented
You'll also need to look at Opendp::makeGroups

2022-05-26 19:52 UTC, maliberty commented
Drop dbRegions as parent's of dbRegions since dbGroups replace that usage.

2022-05-29 19:50 UTC, osamahammad21 commented
> Remove dbInsts from dbRegion as those should be handled by dbGroup.

@maliberty according to the lefdefref, in the COMPONENTS section, the inst could have a REGION option.

2022-05-29 20:57 UTC, maliberty commented
> > Remove dbInsts from dbRegion as those should be handled by dbGroup.
> 
> @maliberty according to the lefdefref, in the COMPONENTS section, the inst could have a REGION option.

Ok but what a horrible model DEF has.

2022-05-30 21:20 UTC, maliberty commented
Please ping me for review again once the CI issues are resolved.

2022-05-31 09:48 UTC, osamahammad21 commented
@maliberty it's just some warnings I'll remove from the ok file. However, while I was editing dpl/test/fence01.ok, I found that this ok file has differences generated in the end between the resulting def and the defok. I think someone just saved the ok files with these generated differences. Should I fix it myself or does this need more investigation by whomever working on dpl?

2022-06-01 04:44 UTC, maliberty approved these changes

2022-06-02 17:06 UTC, merged