OpenROAD Main README.md update
The-OpenROAD-Project/OpenROAD pull request #1975
Opened 2022-06-21 13:50 UTC by vijayank88

It resolves #1953

2022-06-21 14:22 UTC, vvbandeira requested changes

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +Supported by [Efabless](https://efabless.com/)
Make a bullet list

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +timing, placement congestion, CTS.
Add a `## GUI` subsection and join these two paragraphs.

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +`ASAP7` - Predictive FinFET 7nm
Remove empty lines and make a bullet list.

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +`TSMC65` - 65nm
Remove empty lines and make a bullet list.

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +QoR.The PDKs and platform-specific files for these kits cannot be
Missing space `QoR. The`

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +tool with a customizable tcl interface.
`tcl` -> `Tcl`

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +Openroad-flow-scripts supports several public and private PDKs
OpenROAD

2022-06-21 14:22 UTC, vvbandeira commented on README.md
> +[OpenRoad-flow-scripts](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts) -
OpenROAD

2022-06-22 13:42 UTC, vvbandeira commented
Thanks, @vijayank88 LGTM. @QuantamHD do you have any feedback on this and can you confirm this meets the criteria to close the issue?

2022-06-24 07:07 UTC, QuantamHD commented
LGTM otherwise! Looks great

2022-06-24 22:42 UTC, vvbandeira approved these changes

2022-06-24 22:42 UTC, merged