Grt: Congestion report file generation
The-OpenROAD-Project/OpenROAD pull request #2090
Opened 2022-07-26 20:21 UTC by luis201420

2022-07-26 20:24 UTC, maliberty commented
@arlpetergadfort FYI based on your request

2022-07-26 20:25 UTC, maliberty commented
@luis201420 did you resolve the warnings generated by the GUI?

2022-07-26 20:31 UTC, luis201420 commented
> @luis201420 did you resolve the warnings generated by the GUI?

Yes, I resolved it

2022-07-26 20:43 UTC, maliberty requested changes

2022-07-26 20:43 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +      save_congestion_(false),
You should initialize congestion_file_name_(nullptr)

2022-07-26 20:43 UTC, maliberty commented on src/grt/include/grt/GlobalRouter.h
> +  const char * congestion_file_name_;
save_congestion_ is just congestion_file_name_ != nullptr so I don't think you need it.

2022-07-26 20:43 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +  out.open(congestion_file_name_, std::ios::app);
Just std::ofstream out(congestion_file_name_);

2022-07-26 20:43 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +  for (auto & it : congestionGridsH){
clang-format

2022-07-26 20:43 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +     int usage = it.second.second;
const 
here and below

2022-07-26 20:43 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +     out << "( " << dbuToMicrons(rect.xMax()) << ", " << dbuToMicrons(rect.yMax()) << ") on Layer \n";
why are you printing "on Layer" ?

2022-07-26 20:43 UTC, maliberty commented on src/gui/src/drcWidget.cpp
> +    }
Rather than make this congestion specific just allow a layer value like "-" for no value

2022-08-01 17:02 UTC, eder-matheus approved these changes
@maliberty I've helped Luis with clang-format, and I think your other comments were also addressed. I didn't find anything else, so I'm approving it. But we can wait until your final review.

2022-08-01 17:16 UTC, maliberty approved these changes

2022-08-01 17:36 UTC, merged