DRT: saving memory by removing unnecessary setters and variables from…
The-OpenROAD-Project/OpenROAD pull request #2109
Opened 2022-08-02 15:56 UTC by habibayassin

… FrLayer

Signed-off-by: habibayassin <habibayassin@aucegypt.edu>

2022-08-04 07:55 UTC, rovinski commented
I'm guessing the reason for the fake cut/layer is to create an `frLayer` without an underlying `dbTechLayer`, but under what circumstance would one want to do that?

2022-08-07 13:58 UTC, osamahammad21 commented
> I'm guessing the reason for the fake cut/layer is to create an `frLayer` without an underlying `dbTechLayer`, but under what circumstance would one want to do that?

@rovinski The ispd test cases start with the routing layer directly without defining a masterslice layer and a cut layer. For consistency, we create a fake masterslice layer and cut layer before the defined layer stack.

2022-08-07 19:17 UTC, jjcherry56 commented
This doesn't really save any memory because there are only about 15 instances of frLayer.
If you want to really have an impact do the same for frInst and frNet.

2022-08-07 21:54 UTC, osamahammad21 commented
> This doesn't really save any memory because there are only about 15 instances of frLayer.
> 
> If you want to really have an impact do the same for frInst and frNet.

@jjcherry56 Hi james. This is the first step of removing duplication in tritonroute's database as we discussed before. Sure we would do the same with the instances and the netlist, but the layer seemed a good place to start. This is not solely for saving memory, but also to have a unified database.

2022-08-09 16:24 UTC, habibayassin commented
@maliberty

2022-08-09 16:42 UTC, rovinski commented
`getWidth()` and `getMinWidth()` can also be replaced.

2022-08-09 16:49 UTC, habibayassin commented
> `getWidth()` and `getMinWidth()` can also be replaced.

@rovinski I actually tried to replace them, but they are being set with values other than the ones from dbtechlayer->getWidth() or dbtechlayer->getMinWidth()

2022-08-09 17:11 UTC, rovinski commented
How so? It looks like they are:

https://github.com/The-OpenROAD-Project/OpenROAD/blob/a2b9a98b5917fddaa9e99d801328f3f8d0e9d039/src/drt/src/io/io.cpp#L1521-L1528

2022-08-09 17:12 UTC, maliberty requested changes

2022-08-09 17:12 UTC, maliberty commented on src/drt/src/db/tech/frLayer.h
> +  bool getFakeMs() const { return fakeMs;}
These should be 

isFakeCut()
isFakeMasterslice()

M is too much of an abbreviation.  Please change it in the setter and member as well.

2022-08-09 17:12 UTC, maliberty commented on src/drt/src/db/tech/frLayer.h
> +  dbTechLayerType getType() const { return (fakeCut)? dbTechLayerType("cut") : (fakeMs)? dbTechLayerType("masterslice") : db_layer_->getType(); }
Use the enum values rather than string lookup, e.g.

dbTechLayerType("masterslice") -> dbTechLayerType::MASTERSLICE

2022-08-09 17:12 UTC, maliberty commented on src/drt/src/io/io.h
> +  odb::dbTechLayer* masterSliceLayerPtr;
Drop Ptr from the name.

2022-08-09 17:17 UTC, maliberty commented
> How so? It looks like they are:
> 
> https://github.com/The-OpenROAD-Project/OpenROAD/blob/a2b9a98b5917fddaa9e99d801328f3f8d0e9d039/src/drt/src/io/io.cpp#L1521-L1528

Line 1528 is updating minWidth.   io::Parser::initCutLayerWidth() updates width if unset from LEF

2022-08-09 19:36 UTC, rovinski commented
> Line 1528 is updating minWidth. io::Parser::initCutLayerWidth() updates width if unset from LEF

That raises an interesting question. If DRT is working around deficiencies in the loaded database, should drt be making its own modified copy or should it be updating the db? Considering DRT was already copying everything, the answer was obviously yes, but if we merge data with odb, I think it becomes a real question.

Maybe something to be addressed in a different PR.

2022-08-09 20:17 UTC, maliberty commented
@rovinski I think it is something for another PR.  I feel messing with the minWidth reflects a shortcoming in drt itself that should be fixed rather than hacking the constraints.   The other case is more interesting.

2022-08-09 21:52 UTC, habibayassin commented
> How so? It looks like they are:
> 
> https://github.com/The-OpenROAD-Project/OpenROAD/blob/a2b9a98b5917fddaa9e99d801328f3f8d0e9d039/src/drt/src/io/io.cpp#L1521-L1528

it is being set here as well:
https://github.com/The-OpenROAD-Project/OpenROAD/blob/a2b9a98b5917fddaa9e99d801328f3f8d0e9d039/src/drt/src/io/io_parser_helper.cpp#L286

2022-09-05 14:20 UTC, maliberty requested changes

2022-09-05 14:20 UTC, maliberty commented on src/drt/src/db/tech/frLayer.h
> +  dbTechLayerDir getDir() const { return (fakeCut || fakeMasterslice)? dbTechLayerDir("none") : db_layer_->getDirection(); }
Don't use the string constructor, just use the enum

2022-09-05 14:20 UTC, maliberty commented on src/drt/src/db/tech/frLayer.h
> +    if(fakeCut)
clang-format

2022-09-06 03:28 UTC, maliberty approved these changes

2022-09-06 03:29 UTC, maliberty commented
You'll have to fix the build errors but otherwise it looks ok

2022-09-07 08:13 UTC, merged