Rhel support in dependency installer
The-OpenROAD-Project/OpenROAD pull request #2474
Opened 2022-11-08 10:44 UTC by habibayassin

semi support for RHEL 8 because
- qt5 is broken on  rhel 8
- there isn't a specific or-tools release for rhel 8

2022-11-10 08:43 UTC, habibayassin commented
@vvbandeira 
Still need to install:

- [ ] OR-tools 
- [ ] QT5

2022-12-05 16:33 UTC, vvbandeira requested changes

2022-12-05 16:33 UTC, vvbandeira commented on .github/workflows/github-actions-test-rhel-dep-install.yml
> +  # Allows you to run this workflow manually from the Actions tab
This file is no longer needed right?

2022-12-05 16:33 UTC, vvbandeira commented on .github/workflows/github-actions-test-installer.yml
> +  pull_request:
Remove as we don't want to trigger this on every push/PR. I suggested on other PR to trigger only when the relevant files change.

2022-12-05 21:38 UTC, habibayassin commented on .github/workflows/github-actions-test-rhel-dep-install.yml
> +  # Allows you to run this workflow manually from the Actions tab
yes will remove it

2022-12-05 23:47 UTC, vvbandeira approved these changes

2022-12-05 23:48 UTC, merged