Issue forms
The-OpenROAD-Project/OpenROAD pull request #2489
Opened 2022-11-13 22:20 UTC by habibayassin

I will add it in ORFS once it is approved here

2022-11-14 01:07 UTC, maliberty commented
Please include a screen shot of what the form look like.

2022-11-15 14:12 UTC, vvbandeira requested changes

2022-11-15 14:12 UTC, vvbandeira commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        &nbsp;&nbsp;&nbsp;&nbsp;- List the commands used.
I think we can have different entries here. One for "Standalone OR", "With OL", "With ORFS",...

2022-11-15 16:56 UTC, habibayassin commented
> Please include a screen shot of what the form look like.

![image](https://user-images.githubusercontent.com/24894057/201979504-16709a19-2161-47a6-882e-09c83cc5d110.png)
![image](https://user-images.githubusercontent.com/24894057/201979606-0d02f7eb-ab1f-4f68-804a-b77dd28498b8.png)
![image](https://user-images.githubusercontent.com/24894057/201979703-9fa4ae38-ad88-4a8d-90b1-6f04001276f0.png)
![image](https://user-images.githubusercontent.com/24894057/201979791-022bd971-6ce5-428e-8062-a6fcba4d9150.png)

2022-11-16 08:02 UTC, habibayassin commented
Having 3 separate forms:
![image](https://user-images.githubusercontent.com/24894057/202121970-822b59fc-fbfa-434a-af11-41f9e1be1c36.png)

2022-11-16 11:40 UTC, vvbandeira commented
@maliberty please see the prints above from Habiba, also you can try to use [this link](https://github.com/habibayassin/OpenROAD/issues/new/choose) -- works for me at least.

2022-11-16 16:19 UTC, maliberty commented
I tried
```
etc/Env.sh 
Please pull the latest changes and try again, if problem persists file a github issue with the re-producible test case.
```
I was in a git repo so this doesn't seem to work correctly.  "git -C . rev-parse" doesn't generate any output and I don't understand why it should.

2022-11-16 16:56 UTC, vvbandeira commented
> I was in a git repo so this doesn't seem to work correctly. "git -C . rev-parse" doesn't generate any output and I don't understand why it should.

I don't think this is expected to return anything. The goal of the command is make sure that the folder the user is running on is part of a git repo. In other words, the command will error if the user runs the script outside of the repo -- and will print `git commit: unknown, this is not a git repository.\n(Please make sure that you have the latest code changes and add the commit hash in the description)\n`

@maliberty Is your repo on the master branch and updated with upstream? I get this on my mac:
```
%  etc/Env.sh

Git commit: a48aa12e2931724b8e51a65613f6d317fd302a1e
kernel: Darwin 22.1.0
os:             macOS           13.0.1
cmake version 3.24.2
Apple clang version 14.0.0 (clang-1400.0.29.202)
Apple clang version 14.0.0 (clang-1400.0.29.202)
```

2022-11-16 17:00 UTC, maliberty commented
lgtm

2022-11-16 17:04 UTC, vvbandeira approved these changes

2022-11-16 17:04 UTC, merged

2022-11-17 05:00 UTC, rovinski commented
This is great - I definitely did not know about this when I made the bug report for ORFS a while back. Hopefully this improves bug report quality!

@vvbandeira @maliberty Maybe it's too aggressive, but it might be worth considering using this bot https://github.com/marketplace/actions/auto-close-issues to automatically close issues which do not follow the format (and automatically reopen them once they are edited to follow the format).

But before that, maybe a next step is to add a form for "feature requests" and/or "questions".

2022-11-17 13:47 UTC, maliberty commented
Let's hold off on auto-close and see how it goes.  I agree about feature requests.  GH already provides discussions for questions.