grt: add load congestion report tip routing failure
The-OpenROAD-Project/OpenROAD pull request #2761
Opened 2023-01-15 13:34 UTC by oharboe

Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>

2023-01-15 14:05 UTC, gadfort requested changes

2023-01-15 14:05 UTC, gadfort commented on src/grt/src/GlobalRouter.cpp
> +                   "in the GUI and load the congestion.rpt in the DRC viewer.");
You should reference the actual report if you are adding this `congestion_file_name_`. And if it's not set probably don't mention it and keep the message the same as before.

2023-01-17 16:31 UTC, maliberty commented
@gadfort please review/approve

2023-01-17 16:55 UTC, gadfort approved these changes

2023-01-17 18:41 UTC, merged