Adding basic folder structure for DFT tool
The-OpenROAD-Project/OpenROAD pull request #2808
Opened 2023-01-24 00:56 UTC by fgaray

This is the first step for #2784. Nothing functional yet, this is only the basic folder structure without anything implemented yet.

2023-01-24 01:03 UTC, QuantamHD commented
Awesome! Looks good so far. I'll let @maliberty weigh in.

2023-01-24 01:21 UTC, fgaray commented
I fixed the format for OpenRoad.cc but I am not sure why it is failing to build on MacOS

2023-01-24 02:35 UTC, maliberty requested changes

2023-01-24 02:35 UTC, maliberty commented on src/dft/README.md
> +be tested for errors coming from physical imperfections in the tapeout.
```suggestion
This tool is an implementation of Design For Testing. New nets and logic are added to allow IC designs to
be tested for errors in manufacturing.   Physical imperfections can cause hard failures and variability can cause timing errors.
```

2023-01-24 02:35 UTC, maliberty commented on src/dft/README.md
> +* Scan cells that replace your flops with registers that allow us for testing.
```suggestion
* Scan cells that replace flops with registers that allow for testing.
```

2023-01-24 02:35 UTC, maliberty commented on src/dft/include/dft/MakeDft.hh
> +#define DFT_MAKE_DFT_H_
Use "#pragma once"

2023-01-24 02:35 UTC, maliberty commented on src/dft/src/CMakeLists.txt
> +      .
Why is this required?  Why is it public?

2023-01-24 02:35 UTC, maliberty commented on src/OpenRoad.cc
> +  dft::deleteDft(dft_);
Non-standard but probably better.

2023-01-24 02:35 UTC, maliberty commented
You'll need to dft add to
https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/docs/contrib/Logger.md
https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/utl/include/utl/Logger.h

2023-01-24 02:36 UTC, maliberty commented
Is this just for review?

2023-01-24 02:37 UTC, maliberty commented
Mac failure:
```
/Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/build/src/dft/src/CMakeFiles/dft.dir/dftTCL_wrap.cxx:1754:10: fatal error: 'dft/Dft.hh' file not found
2023-01-24T01:23:00.7089340Z #include "dft/Dft.hh"
2023-01-24T01:23:00.7090090Z          ^~~~~~~~~~~~
2023-01-24T01:23:00.8152330Z 1 error generated.
2023-01-24T01:23:00.8261980Z make[2]: *** [src/dft/src/CMakeFiles/dft.dir/CMakeFiles/dft.dir/dftTCL_wrap.cxx.o] Error 1
```

2023-01-24 03:02 UTC, fgaray commented on src/dft/include/dft/MakeDft.hh
> +#define DFT_MAKE_DFT_H_
Yeah, I notice that in the code, but I wonder if it is better to migrate to this instead of using #pragma once?, AFAIK pragma one is not standard.

2023-01-24 04:26 UTC, maliberty commented on src/dft/include/dft/MakeDft.hh
> +#define DFT_MAKE_DFT_H_
No we do not intend to migrate. All modern compilers support it

2023-01-24 06:13 UTC, QuantamHD commented
@maliberty Googlers are used to submitting code in small increments. I expect that @fgaray would prefer you that you merged in the boiler plate, and then he could add onto it in a new PR.

It's a very common practice especially for webservers/apis. Typically you would send all the boiler plate in with a stubbed response and submit that. 

In Google our code review tool allowa you to stack PRs on top of each other. GitHub doesn't allow you to do such things which can make these workflows a bit more awkward.

In open source there's typically a higher bar to get code in because contributors can come and go as they please. The idea of small PRs is to reduce the review burden. So it just depends on if that would be helpful or not.

2023-01-24 06:33 UTC, maliberty commented
I hate getting one huge PR so I like breaking into steps.  I'm ok so long as there is a clear commitment to reaching a useable milestone.  I think it will slow your progress to have to wait on reviews so there is probably some happy medium in terms of size.

Note https://blog.logrocket.com/using-stacked-pull-requests-in-github/ suggests another workflow that might be closer to what google does.

2023-01-25 00:28 UTC, fgaray commented on src/dft/src/CMakeLists.txt
> +      .
It was not required, I removed and moved the CMakeLists.txt to the upper directory

2023-01-25 00:28 UTC, fgaray commented on src/dft/include/dft/MakeDft.hh
> +#define DFT_MAKE_DFT_H_
That's fair!, I changed the header guards to #pragma once

2023-01-25 00:41 UTC, fgaray commented
Thanks @QuantamHD for the context! It makes sense that in an Open Source project we want to accept more atomic PRs. If @maliberty is fine, we can submit this PR and next time I will try to use something like what you suggested (https://blog.logrocket.com/using-stacked-pull-requests-in-github/) so you can see the feature that I want to contribute more complete.

@maliberty I think I fixed and resolved all your comments, so it is ready for review.

2023-01-25 04:38 UTC, maliberty requested changes

2023-01-25 04:38 UTC, maliberty commented on src/utl/include/utl/Logger.h
> +  X(DFT)
Please put in alphabetical order

2023-01-25 04:39 UTC, maliberty commented on src/dft/include/dft/MakeDft.hh
> +#define pragma once
It is just 
```
#pragma once
```

2023-01-25 06:55 UTC, rovinski commented on src/utl/include/utl/Logger.h
> +  X(DFT)
PAD needs to move down 3 spots then

2023-01-25 17:46 UTC, fgaray commented on src/utl/include/utl/Logger.h
> +  X(DFT)
I sorted all the list

2023-01-26 03:18 UTC, maliberty approved these changes

2023-01-26 03:18 UTC, merged