gui: add aggregate net descriptor
The-OpenROAD-Project/OpenROAD pull request #2824
Opened 2023-01-29 20:26 UTC by gadfort

https://github.com/The-OpenROAD-Project/OpenROAD/issues/2781

2023-01-30 20:11 UTC, maliberty commented
This looks like a bug as the aggregate is VDD:
![image](https://user-images.githubusercontent.com/761514/215584615-e5035868-b2db-486d-a143-8c28752063c0.png)

2023-01-30 20:13 UTC, maliberty commented on src/gui/src/aggregateNetDescriptor.cpp
> +    }
I expect the bug is here in not checking whether the iterm is power/gnd

2023-01-30 20:14 UTC, gadfort commented on src/gui/src/aggregateNetDescriptor.cpp
> +    }
Yeah, you are correct, supplies shouldn't be in the list.

2023-01-30 20:18 UTC, maliberty commented on src/gui/src/aggregateNetDescriptor.cpp
> +    }
if (!next_iterm->getSigType().isSupply()) {
        populate(next_iterm->getNet());
      }

seems to work

2023-01-30 20:23 UTC, maliberty commented
After the discussion in the issue I did come to like "Buffer tree" better than "Aggregate Net".   Perhaps it could include the buffer instances as well as the nets.

2023-01-30 21:25 UTC, maliberty commented
Also the non-buffer iterm/bterms would be nice (like a regular net) to see where the tree terminates.

2023-01-31 00:01 UTC, gadfort commented
@maliberty I renamed it to Buffer Tree, added iterms/bterms and instances to the descriptor (they are not part of the highlight though). Route guides and focus nets is also there.

2023-01-31 00:25 UTC, maliberty requested changes
I am really finding this helpful.  Thanks!

2023-01-31 00:25 UTC, maliberty commented on src/gui/src/dbDescriptors.cpp
> +    props.push_back({"Aggregate net", gui->makeSelected(BufferTree(net))});
There is still some use of Aggregate in the code and visible in the GUI

2023-01-31 00:25 UTC, maliberty commented on src/gui/src/bufferTreeDescriptor.cpp
> +  name_ = nets_[0]->getName();
std::min_element is more efficient than sort

2023-01-31 00:25 UTC, maliberty commented on src/gui/src/bufferTreeDescriptor.cpp
> +    }
A std::set would be more efficient than linear search of a vector.

2023-01-31 00:25 UTC, maliberty commented on src/gui/src/bufferTreeDescriptor.cpp
> +  return l_anet->getName() < r_anet->getName();
anet needs updating

2023-01-31 00:26 UTC, maliberty commented
Free bonus, If you click a clock net you get the clock tree:
![image](https://user-images.githubusercontent.com/761514/215627200-7ff41421-ca8c-4c8a-9053-dc9d10d61f25.png)

2023-01-31 02:40 UTC, gadfort commented on src/gui/src/bufferTreeDescriptor.cpp
> +  name_ = nets_[0]->getName();
The sort is used to ensure a stable ordering of the nets.

2023-01-31 02:44 UTC, gadfort commented
Feedback should be addressed

2023-01-31 04:08 UTC, maliberty approved these changes

2023-01-31 04:09 UTC, merged