drt: Ensure vias conform to WIDTHTABLE constraints
The-OpenROAD-Project/OpenROAD pull request #3056
Opened 2023-03-21 09:54 UTC by antonblanchard

2023-03-21 15:45 UTC, rovinski commented on src/drt/src/io/io_parser_helper.cpp
> +  // We ignore vias with default width pads because they wont cause width table
Is "pads" the right term here? Do you mean "enclosure metals"?

2023-03-21 21:36 UTC, maliberty requested changes

2023-03-21 21:36 UTC, maliberty commented on src/drt/src/io/io_parser_helper.cpp
> +                            int width,
const method and width is a const argument

isValidWidth makes more sense for a predicate

2023-03-21 21:36 UTC, maliberty commented on src/drt/src/io/io_parser_helper.cpp
> +bool io::Parser::viaWidthsValid(frViaDef* viaDef)
isViaWidthsValid

2023-03-21 21:36 UTC, maliberty commented on src/drt/src/io/io_parser_helper.cpp
> +}
just return the expression, no need for

```
if (...) {
  return true;
}
return false;
```

2023-03-23 18:48 UTC, maliberty commented
Replaced by https://github.com/The-OpenROAD-Project/OpenROAD/pull/3059

2023-03-23 18:48 UTC, closed without merging