pin swapping + Vth (V0)
The-OpenROAD-Project/OpenROAD pull request #3215
Opened 2023-04-20 03:44 UTC by openroadie

2023-04-20 22:36 UTC, maliberty requested changes

2023-04-21 00:58 UTC, QuantamHD commented
In the future I think it would be good to break up Resizer.cc into multiple files. It's kind of turning into a giant God file.

2023-04-21 03:09 UTC, openroadie commented on src/rsz/include/rsz/Resizer.hh
>    float max_wire_length_;
I can remove the comment if (which reflects my understanding of it when I looked at it last). I would rather not get into the details of this within this PR (if that is ok). LMK

2023-04-21 03:11 UTC, openroadie commented on src/rsz/src/Resizer.cc
> +    LibertyPort *port1, *port2;
It was really off by 3 lines. Not sure if that makes a whole lot of difference.

2023-04-21 04:28 UTC, maliberty commented on src/rsz/src/Resizer.cc
> +    LibertyPort *port1, *port2;
Not that big in this case but I mention it so you are aware of the preferred coding style.

2023-04-21 04:31 UTC, maliberty commented on src/rsz/include/rsz/Resizer.hh
>    float max_wire_length_;
I can live with it.  I find the whole idea confusing at best.

2023-04-21 04:35 UTC, maliberty commented on src/rsz/src/Resizer.cc
> +    LibertyPort *port1, *port2;
You didn't get the idea it seems.  

874: Net *net1, *net2;
....
886:  net1 = net2 = nullptr;

Just move the definition to 886.  Ditto the others.

2023-04-21 05:20 UTC, openroadie commented on src/rsz/include/rsz/Resizer.hh
>    float max_wire_length_;
I will address it in a future PR.  I agree with you.

2023-04-21 05:24 UTC, openroadie commented on src/rsz/src/Resizer.cc
> +            port1 = port;
Confused myself with variable names. Will fix. Thanks :)

2023-04-24 17:58 UTC, maliberty approved these changes

2023-04-24 17:58 UTC, merged