Opensta upgrade
The-OpenROAD-Project/OpenROAD pull request #3341
Opened 2023-05-16 15:24 UTC by openroadie

2023-05-16 15:34 UTC, maliberty commented
Please run a secure CI for this

2023-05-16 15:41 UTC, openroadie commented
All regressions in OpenROAD/test pass with the code in this PR

> Please run a secure CI for this

Ok. So if I recall the process right:

- Make a branch in the private repo... make sure it is called "Secure" something 
- Commit the same code into that branch
- Wait for you secure-ci to finish.

Let me know if I missed anything.

2023-05-16 15:42 UTC, maliberty commented
Yes - in the private ORFS repo.

2023-05-20 17:51 UTC, QuantamHD commented on src/gpl/test/simple01-td.ok
> +    - _276_ NOR2_X2 + PLACED ( 9965 51825 ) N ;
Differences shouldn't be added to golden files.

2023-06-15 18:52 UTC, maliberty commented
I'm not sure why it only shows up in mac but:
```
2023-06-15T18:28:47.7178460Z /Users/openroad/github-action-runners/actions-runner-1/_work/OpenROAD/OpenROAD/src/gui/src/chartsWidget.cpp:212:54: error: no member named 'scaleAbreviation' in 'sta::Unit'; did you mean 'scaleAbbreviation'?
```

2023-06-15 20:44 UTC, maliberty requested changes

2023-06-15 20:44 UTC, maliberty commented on src/gpl/test/simple01-td-tune.ok
> +    - _276_ NOR2_X2 + PLACED ( 10227 53342 ) N ;
Needs fixing

2023-06-16 04:33 UTC, openroadie commented on src/gpl/test/simple01-td-tune.ok
> +    - _276_ NOR2_X2 + PLACED ( 10227 53342 ) N ;
Done.

2023-06-17 14:19 UTC, maliberty commented
Does this make sense in light of #3476 ?  Wouldn't that include this as well?

2023-06-17 14:21 UTC, maliberty commented
I don't see a secure CI result for this.  What branch name was used?

2023-06-17 15:34 UTC, openroadie commented
Yes. Don’t we have a policy of many small PRs. The previous PR is already
one month old. So let’s merge that and then worry about this incremental
change

On Sat, Jun 17, 2023 at 7:19 AM Matt Liberty ***@***.***>
wrote:

> Does this make sense in light of #3476
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476> ? Wouldn't
> that include this as well?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595772670>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-17 15:36 UTC, openroadie commented
I will do do a secure ci. Let’s close on the other one which now has
everything needed to merge. We don’t want to get caught with no upgrades
should secure ci show us problems with this pr
On Sat, Jun 17, 2023 at 7:21 AM Matt Liberty ***@***.***>
wrote:

> I don't see a secure CI result for this. What branch name was used?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595773140>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MSTIZ7SCIEBCGJO6XXDRLXLW4QHANCNFSM6AAAAAAYD2JDTI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-17 16:04 UTC, maliberty commented
I don't see a secure ci.  If you have one that's fine but if you have to
start another it seems simpler to do it once.  If you prefer to do them
serially that's fine too.

On Sat, Jun 17, 2023 at 8:34 AM Harsh Vardhan ***@***.***>
wrote:

> Yes. Don’t we have a policy of many small PRs. The previous PR is already
> one month old. So let’s merge that and then worry about this incremental
> change
>
> On Sat, Jun 17, 2023 at 7:19 AM Matt Liberty ***@***.***>
> wrote:
>
> > Does this make sense in light of #3476
> > <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476>
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xkx2VK7Kg$>
> ? Wouldn't
> > that include this as well?
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595772670>
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595772670*3E__;IyU!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xnC3IbJrg$>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI>
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl1ruh1DA$>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595789291__;Iw!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl2ui_Ztw$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAFZ5KWPNV3STWBJOWHFOO3XLXFB5ANCNFSM6AAAAAAYD2JDTI__;!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xlpihu4DQ$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-17 16:06 UTC, openroadie commented
The original pr was held up because of secure ci and issues with routing
etc or do you not remember that ? I will find out the branch name and post
here if you cannot find it


On Sat, Jun 17, 2023 at 9:04 AM Matt Liberty ***@***.***>
wrote:

> I don't see a secure ci. If you have one that's fine but if you have to
> start another it seems simpler to do it once. If you prefer to do them
> serially that's fine too.
>
> On Sat, Jun 17, 2023 at 8:34 AM Harsh Vardhan ***@***.***>
> wrote:
>
> > Yes. Don’t we have a policy of many small PRs. The previous PR is
> already
> > one month old. So let’s merge that and then worry about this incremental
> > change
> >
> > On Sat, Jun 17, 2023 at 7:19 AM Matt Liberty ***@***.***>
> > wrote:
> >
> > > Does this make sense in light of #3476
> > > <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476>
> > <
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xkx2VK7Kg$>
>
> > ? Wouldn't
> > > that include this as well?
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595772670>
>
> > <
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595772670*3E__;IyU!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xnC3IbJrg$>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI>
>
> > <
> https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl1ruh1DA$>
>
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595789291__;Iw!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl2ui_Ztw$>,
>
> > or unsubscribe
> > <
> https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAFZ5KWPNV3STWBJOWHFOO3XLXFB5ANCNFSM6AAAAAAYD2JDTI__;!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xlpihu4DQ$>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595794988>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MSTI6Q6NKKHTKKUO5MIYDXLXISRANCNFSM6AAAAAAYD2JDTI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-17 16:25 UTC, maliberty commented
If I could find it I wouldn't have asked.

On Sat, Jun 17, 2023 at 9:07 AM Harsh Vardhan ***@***.***>
wrote:

> The original pr was held up because of secure ci and issues with routing
> etc or do you not remember that ? I will find out the branch name and post
> here if you cannot find it
>
>
> On Sat, Jun 17, 2023 at 9:04 AM Matt Liberty ***@***.***>
> wrote:
>
> > I don't see a secure ci. If you have one that's fine but if you have to
> > start another it seems simpler to do it once. If you prefer to do them
> > serially that's fine too.
> >
> > On Sat, Jun 17, 2023 at 8:34 AM Harsh Vardhan ***@***.***>
> > wrote:
> >
> > > Yes. Don’t we have a policy of many small PRs. The previous PR is
> > already
> > > one month old. So let’s merge that and then worry about this
> incremental
> > > change
> > >
> > > On Sat, Jun 17, 2023 at 7:19 AM Matt Liberty ***@***.***>
> > > wrote:
> > >
> > > > Does this make sense in light of #3476
> > > > <https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476>
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476*3E__;JQ!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qmT_PiBkw$>
> > > <
> >
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3476*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xkx2VK7Kg$%3E
> >
> > > ? Wouldn't
> > > > that include this as well?
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595772670>
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595772670*3E__;IyU!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qkL0R2tgw$>
> >
> > > <
> >
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595772670*3E__;IyU!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xnC3IbJrg$%3E,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI>
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI*3E__;JQ!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qnShQZUwQ$>
> >
> > > <
> >
> https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A3MSTI2JC4BOS4E7T4GE3D3XLW4IHANCNFSM6AAAAAAYD2JDTI*3E__;JQ!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl1ruh1DA$%3E
> >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595789291__;Iw!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xl2ui_Ztw$%3E,
>
> >
> > > or unsubscribe
> > > <
> >
> https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAFZ5KWPNV3STWBJOWHFOO3XLXFB5ANCNFSM6AAAAAAYD2JDTI__;!!Mih3wA!DMf12x_eD5TIW4R83JQHDK9gl32QyX-2OPgUvLruYNhe6IsveV5dGvY2d78YFqLlKki7TgSGGD2ILBPc7xlpihu4DQ$%3E
> >
> > > .
> > > You are receiving this because you were mentioned.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341#issuecomment-1595794988>
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595794988*3E__;IyU!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qlHcV_JLg$>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A3MSTI6Q6NKKHTKKUO5MIYDXLXISRANCNFSM6AAAAAAYD2JDTI>
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A3MSTI6Q6NKKHTKKUO5MIYDXLXISRANCNFSM6AAAAAAYD2JDTI*3E__;JQ!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qlTC4H4vg$>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/The-OpenROAD-Project/OpenROAD/pull/3341*issuecomment-1595795353__;Iw!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qkxVHKIOA$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAFZ5KW6YAPOOG75OMPN7ZDXLXIZXANCNFSM6AAAAAAYD2JDTI__;!!Mih3wA!H221ils03Dufxre5GUYNjpGZCTBLBlm-7s2bShb3TrWfcOboDnYcES_VRp1sjiZXtYKptahBtqBzNzKD1qlxSqzKNg$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-17 16:42 UTC, maliberty commented
The result is likely too old to be meaningful.  I'll merge this and the next and we can deal with the fallout afterwards.  The drt fix had to be reverted anyways so this will fail again.

2023-06-17 16:42 UTC, maliberty approved these changes

2023-06-17 16:42 UTC, merged