dpl: Move Grid from pointers to vectors
The-OpenROAD-Project/OpenROAD pull request #3438
Opened 2023-06-07 22:40 UTC by QuantamHD

I found a destructor related bug in one of Google's test cases. Rather than debug it I figured I'd just move it to vector, and not worry about it.

2023-06-07 22:48 UTC, maliberty requested changes
I would have opted for boost::multi_array which is more efficient than either solution.

2023-06-07 22:48 UTC, maliberty commented on src/dpl/src/Grid.cpp
> -void Opendp::deleteGrid()
This should do "grid_.clear();"

2023-06-07 23:12 UTC, QuantamHD commented
> I would have opted for boost::multi_array which is more efficient than either solution.

Seems like a good idea, but this one is about correctness, and not performance.

2023-06-08 00:03 UTC, QuantamHD commented
@maliberty Is this good to go?

2023-06-08 01:47 UTC, maliberty approved these changes

2023-06-08 01:48 UTC, merged