gui: add offset between die and the end of the viewport
The-OpenROAD-Project/OpenROAD pull request #3610
Opened 2023-07-12 14:10 UTC by AcKoucher

Resolves #3333.

2023-07-12 18:08 UTC, gadfort requested changes
It might be better to cache the size in DBUs for the largest/longest pin name and update it on zooming so it's not a hardcoded constant.

2023-07-12 18:08 UTC, gadfort commented on src/gui/src/layoutViewer.h
> +  const int marker_text_offset_ = 15000;
not a fan of magic numbers. how does this work if the dbuPerMicron is different?

2023-07-12 18:08 UTC, gadfort requested changes
It might be better to cache the size in DBUs for the largest/longest pin name and update it on zooming so it's not a hardcoded constant.

2023-07-12 20:07 UTC, AcKoucher commented
As the name is just a string, is there a way to convert the width of the string directly to dbu? I just know how to get the size in pixels with Qt using `QFontMetrics::horizontalAdvance(QString qstr)`.

2023-07-12 20:17 UTC, gadfort commented
If you have the number of pixels, you can can convert that to DBUs with `getPixelsPerDBU()`
```
QFontMetrics::horizontalAdvance(QString qstr) / getPixelsPerDBU()
```

2023-07-13 18:52 UTC, AcKoucher commented
I am trying to follow the instruction to cache the size of the longest text in DBU, but I am having some difficulties understanding how to do that.
Do the pin texts have a fixed size in DBU like the other objects from db? It looks like the texts have a fixed size in pixels (that I can get using the Qt method of my previous comment), so:
If the texts don't have a fixed size in DBU and the only way to know it is by converting as you showed, it seems complicated, because `getBounds()` is used to compute the new `pixels_per_dbu_` on which the text size in dbu depends.

2023-07-14 06:31 UTC, Iyury1 commented
I think the pin texts are being drawn in RenderThread::drawPinMarkers(). The text comes from odb::dbBterm::getName() on line 1441 which returns a std::string, so I suppose it would need to be converted to a QString first and then you could use the conversion @gadfort mentioned.

2023-07-14 17:58 UTC, AcKoucher commented
Maybe I'm having difficulties expressing myself:
The problem is: to add the correct offset to the bounds, we need to know the size of the text in DBU, but to know the size of the text in DBU we need the value in pixels_per_dbu_, which is calculated using the bounds. One thing depends on the other.

@gadfort I'm sorry if this is getting too confusing.

@Iyury1 I appreciate the comment, but I think I know how to make the conversion:

```
void LayoutViewer::generateLongestPinName()
{
  QFont marker_font = options_->pinMarkersFont();
  QFontMetrics font_metrics(marker_font);

  std::vector<int> text_sizes;

  for (auto term : block_->getBTerms()) {
    QString pin_text = QString::fromStdString(term->getName());
    text_sizes.push_back(font_metrics.width(pin_text));
  }

  auto longest_text = std::max_element(text_sizes.begin(),
                                       text_sizes.end());

  pin_longest_text_ = *longest_text/pixels_per_dbu_;
}
```

2023-07-14 19:33 UTC, gadfort commented
@AcKoucher It looks like we allocate 2% of the boundary to draw the markers: https://github.com/The-OpenROAD-Project/OpenROAD/blob/dcfd631a4a67c225e5a13372a33b27ae0d024c25/src/gui/src/renderThread.cpp#L1291

Maybe the solution isn't to add an additional offset, but to correct this code to ensure the text will get scaled to ensure it fits properly in the space allotted?

2023-07-14 19:48 UTC, AcKoucher commented
I agree with you, I think this is solution. I'll take a look at it. Thanks!

2023-07-18 20:47 UTC, maliberty requested changes
@gadfort any further concerns?

2023-07-18 20:47 UTC, maliberty commented on src/gui/src/renderThread.cpp
> +  std::vector<int> text_lenghts;
typo: text_lenghts -> text_lengths

2023-07-27 22:11 UTC, maliberty commented on src/gui/src/renderThread.cpp
> +      = std::max_element(text_widths.begin(), text_widths.end());  // pixels
Building a vector to just take the max is quite wasteful.  Just compute the max as you go and skip all the memory allocations.  Same below.

2023-07-27 22:12 UTC, maliberty commented
The gui feels noticeable slower when I use this branch.  I'm not sure if it the vector noted above or the sizing loop or both.

2023-07-28 21:07 UTC, AcKoucher commented
I removed the unneeded allocations and, instead of iterating inside the size loop, I kept the largest text in a string to compute the new size based on the font. It improved a lot, but I think I can still feel a little slower than master, in one or two specific ranges of zoom particularly.

2023-07-31 21:24 UTC, maliberty commented
Something is broken - if I zoom in:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/4d4729fe-b339-4130-9bd7-db062f47bc93)

2023-08-08 20:14 UTC, maliberty approved these changes

2023-08-08 20:14 UTC, merged