[Docs] rsz documentation
The-OpenROAD-Project/OpenROAD pull request #3701
Opened 2023-07-23 09:05 UTC by luarss

Fixes missing functions and formatting.

2023-07-23 21:46 UTC, rovinski commented on src/rsz/README.md
> +| `-resistance` | resistance per unit length, same convention as `set_wire-rc` |
```suggestion
| `-resistance` | resistance per unit length, same convention as `set_wire_rc` |
```

2023-07-23 21:56 UTC, rovinski commented on src/rsz/README.md
> +| `-resistance` | resistance per unit length, units are from the first Liberty file read, usually in the form of $\frac{resistanceUnit}{distanceUnit}$. Usually kΩ/µm. |
Where is capacitance?

2023-07-23 21:56 UTC, rovinski commented on src/rsz/README.md
> +    [-resistance res]
Might as well order it resistance then capacitance to match order of `set_wire_rc`

2023-07-23 21:56 UTC, rovinski commented on src/rsz/README.md
> +| `-resistance` | resistance per unit length, same convention as `set_wire-rc` |
Also same note about ordering

2023-08-23 18:07 UTC, vvbandeira requested changes
PR has merge conflict

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +| `-layer` | If `-layer` is used, the LEF technology resistance and area/edge capacitance values for the layer are used for a default width wire on the layer. |
```suggestion
| `-layer` | Use the LEF technology resistance and area/edge capacitance values for the layer. This is used for a default width wire on the layer. |
```

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +| `-corner` | Process corner to use. |
```suggestion
| `-layer` | Set layer name to modify. Note that the layer must be a routing layer. |
| `-via` | Select via layer name. Note that via resistance is per cut/via, not area-based. |
| `-resistance` | Resistance per unit length, same convention as `set_wire_rc`. |
| `-capacitance` | Capacitance per unit length, same convention as `set_wire_rc`. |
| `-corner` | Process corner to use. |
```

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +| `-cap_margin` | Add a capactitance margin (0-100, integer). |
Default and range formatting.

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +### Useful developer functions
```suggestion
### Useful Developer Commands
```

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +repair_setup_pin end_pin
Table

2023-08-23 18:07 UTC, vvbandeira commented on src/rsz/README.md
> +There are a set of regression tests in `/test`. For more information, refer to this [section](../../README.md#regression-tests).
```suggestion
There are a set of regression tests in `./test`. For more information, refer to this [section](../../README.md#regression-tests). 
```

2023-08-25 17:34 UTC, vvbandeira approved these changes

2023-08-25 17:35 UTC, merged