[Docs] rcx documentation
The-OpenROAD-Project/OpenROAD pull request #3718
Opened 2023-07-25 10:54 UTC by luarss

Fix missing documentation and formatting issues

2023-07-25 17:47 UTC, rovinski commented on src/rcx/README.md
> +| `cc_model` | specify the maximum number of tracks of lateral context that the tool considers on the same routing level (default 10). |
```suggestion
| `-cc_model` | specify the maximum number of tracks of lateral context that the tool considers on the same routing level (default 10). |
```

2023-08-02 13:32 UTC, vvbandeira requested changes

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | filename containing process corner |
```suggestion
| `-ext_model_index` | Extraction model index. |
| `filename` | Path to file containing process corner. |
```

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | filename containing process corner |
What is the expected file format/ext?

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `-no_merge_via_res` | separates the via resistance from the wire resistance.|
```suggestion
| `-ext_model_file` | Specify the Extraction Rules file used for the extraction. |
| `-corner_cnt` | Defines the number of corners used during the parasitic extraction (default 1). |
| `-max_res` | Combines resistors in series up to the threshold value (default 50). |
| `-coupling_threshold` | Coupling below this threshold is grounded (default 0.1, units: fF). |
| `-lef_res` | Override LEF resistance per unit. |
| `-cc_model` | Specify the maximum number of tracks of lateral context that the tool considers on the same routing level (default 10). |
| `-context_depth` | Specify the number of levels of vertical context that OpenRCX needs to consider for the over/under context overlap for capacitance calculation (default 5). |
| `-no_merge_via_res` | Separates the via resistance from the wire resistance.|
```

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `-no_merge_via_res` | separates the via resistance from the wire resistance.|
Missing `-debug_net_id` for developers.

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | the output filename |
Capitalize and add a period at the end.

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `gndc_factor` | specifies the scale factor for ground capacitance. |
Capitalize and add prefix `-`

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `r_conn` | read connections |
```suggestion
| `-file` | Path to the input `.spef` file. |
| `-r_res` | read resistance |
| `-r_cap` | read capacitance |
| `-r_cc_cap` | read coupled capacitance |
| `r_conn` | read connections |
```

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `r_conn` | read connections |
Capitalize, add a period.

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `over_dist`, `under_dist` | over and under metal distance respectively |
Capitalize, prefix `-`, period at the end.

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | output `.v` filename |
```suggestion
| `filename` | Name for the Verilog output file `.v`. |
```

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | input `.spef` filename |
```suggestion
| `filename` | Path to the input `.spef` file. |
```

2023-08-02 13:32 UTC, vvbandeira commented on src/rcx/README.md
> +| `-pattern` | flag to write the pattern to rulefile (0/1) |
Capitalize, add a period at the end.

2023-08-23 20:45 UTC, vvbandeira requested changes

2023-08-23 20:45 UTC, vvbandeira commented on src/rcx/README.md
> +| `filename` | Name for the Verilog output file `.v`. |
```suggestion
| `filename` | Name for the Verilog output file (e.g., `output.v`). |
```

2023-08-24 11:38 UTC, merged