DO NOT MERGE. Doxygen test 2
The-OpenROAD-Project/OpenROAD pull request #3831
Opened 2023-08-09 15:17 UTC by luarss

@vvbandeira Doxygen template 2 test.

2023-08-09 19:40 UTC, luarss commented
@vvbandeira The link works now.

https://openroad--3831.org.readthedocs.build/en/3831/api/odb.html
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/1352c3a9-39d4-46f1-8169-1ec254fc30b8)

2023-08-09 21:51 UTC, vvbandeira commented
Thanks this is great. Is it possible to make the "Main Page" go back to https://openroad--3831.org.readthedocs.build/en/3831/?

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/9001905/ae07d4da-7ad7-4328-b17b-41771935ecd3)

2023-08-12 11:47 UTC, luarss commented
@vvbandeira Now it has the link back to the docs on the mainpage

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/acbdc98d-6905-404a-af4e-62f65cfe52f5)

2023-08-12 12:05 UTC, luarss commented
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/fe6a62a5-ea68-47ed-9217-6a98fd378a5c)

2023-08-24 14:12 UTC, vvbandeira requested changes

2023-08-24 14:12 UTC, vvbandeira commented on Doxyfile
This is too verbose. Please keep up to line 19 + any non-default value.

2023-08-24 14:12 UTC, vvbandeira commented on docs/conf.py
> +html_static_path = ['_static', './build/html']
is this still needed in the latest version?

2023-08-24 19:24 UTC, mithro commented
Random comment - Doxygen comments can be imported into Sphinx documentation using exhale - https://exhale.readthedocs.io/en/latest/ -- Verilog to Routing docs uses it --> https://docs.verilogtorouting.org

2023-08-25 14:03 UTC, luarss commented on docs/odb.md
> +To go back to OpenROAD documentation, follow this [link](../../index.html).
It is redirecting to the OpenROAD main page. Not sure what you mean by generic?

2023-08-25 14:06 UTC, luarss commented on docs/odb.md
> +To go back to OpenROAD documentation, follow this [link](../../index.html).
Do you mean changing the filename to something generic?

2023-08-25 14:20 UTC, vvbandeira commented on docs/odb.md
> +To go back to OpenROAD documentation, follow this [link](../../index.html).
Yes, the file name should probably de `docs/index_doxygen.md` and the section header `# OpenROAD Source Code Documentation` or something with developer in the name.

2023-08-25 14:24 UTC, closed without merging

2023-08-25 14:24 UTC, luarss commented
Closed for now because RTD is not generating new docs.

2023-08-25 15:03 UTC, luarss commented on docs/conf.py
> +html_extra_path = ['./build/html']
No to this and above. have reflected in latest PR.

2023-08-25 17:05 UTC, vvbandeira commented
Replaced by #3905