[Docs] TOC changes + Database Math
The-OpenROAD-Project/OpenROAD pull request #3860
Opened 2023-08-15 07:30 UTC by luarss

@dralabeing @vvbandeira 

Please review if the TOC are to spec and Database math section is rewritten appropriately.

2023-08-15 17:45 UTC, vvbandeira submitted a review, later dismissed

2023-08-15 17:45 UTC, vvbandeira commented
@dralabeing looks good to me, any thoughts?

2023-08-15 20:04 UTC, dralabeing commented
> @dralabeing @vvbandeira
> 
> Please review if the TOC are to spec and Database math section is rewritten appropriately.

I still see personal statements in Database Math.

2023-08-15 21:46 UTC, QuantamHD commented
Could we add a symlink CONTRIBUTING.md to the root of the repo pointing to this documentation.

2023-08-16 00:56 UTC, luarss commented
> > @dralabeing @vvbandeira
> > Please review if the TOC are to spec and Database math section is rewritten appropriately.
> 
> I still see personal statements in Database Math.

@dralabeing Do you mind listing which areas I should change?

2023-08-16 01:01 UTC, luarss commented
> Could we add a symlink CONTRIBUTING.md to the root of the repo pointing to this documentation?

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/fd302e9a-e434-4a05-a48d-0c78463938f8)

Not too sure if we should do this, as our repo never had a `CONTRIBUTING.md` file. We have a contributor guide section in the docs, and it covers more details than just developer math.

2023-08-16 19:34 UTC, dralabeing commented
> > Could we add a symlink CONTRIBUTING.md to the root of the repo pointing to this documentation?
> 
> ![image](https://user-images.githubusercontent.com/39641663/260873696-fd302e9a-e434-4a05-a48d-0c78463938f8.png)
> 
> Not too sure if we should do this, as our repo never had a `CONTRIBUTING.md` file. We have a contributor guide section in the docs, and it covers more details than just developer math.

Move Parasitic Extraction after Metal Fill - sorry if this was not done correctly earlier

2023-08-16 19:48 UTC, dralabeing commented on docs/contrib/DatabaseMath.md
> +It has been noticed that some programs use `double` to calculate distances.
Some of these are programmatic guidelines like in this case of using double to calculate distances. I suggest making these as a Guidelines section and adding a bulleted list that looks like this:
. Don't use double to calculate distances, Use int64_t instead. in one or 2 sentences explain the impact...

2023-08-16 19:49 UTC, dralabeing commented on docs/contrib/DatabaseMath.md
> +This can be problematic, as `double` have a mantissa of 52 bits, which means that
Too long an explanation- condense this to two or three short sentences. We can discuss this offline

2023-08-16 19:49 UTC, dralabeing commented on docs/contrib/DatabaseMath.md
> +### Use int only for LEF/DEF Distances
Again, this is a guideline for distance definition for LEF.

2023-08-16 19:51 UTC, dralabeing commented on docs/contrib/DatabaseMath.md
> +
This is the most important guideline for coding distances that should be front and center.

2023-08-16 19:53 UTC, dralabeing reviewed
Database Math should be structured as coding guidelines rather than the long narrative of wrong usage.

2023-08-18 03:12 UTC, luarss commented
@dralabeing implemented the changes discussed yesterday.

2023-08-18 12:42 UTC, vvbandeira requested changes

2023-08-18 12:42 UTC, vvbandeira commented on docs/toc.yml
> +    title: Getting Started with the OpenROAD flow - OpenROAD-flow-scripts
```suggestion
    title: Getting Started with the OpenROAD Flow - OpenROAD-flow-scripts
```

2023-08-18 12:42 UTC, vvbandeira commented on docs/toc.yml
> +        title: VSRC description
```suggestion
        title: VSRC Description
```

2023-08-18 12:42 UTC, vvbandeira commented on docs/contrib/DeveloperGuide.md
> +and `int64_t` for all area calculations. For a more detailed writeup, refer to this [link](DatabaseMath.md).
```suggestion
1. Internally, the code should use `int` for all database units and `int64_t`
for all area calculations. Refer to this [link](DatabaseMath.md) for a more
detailed writeup on the reasons why this approach is preferred. The only
place that the database distance units should appear in any program
should be in the user interface, as microns are easier for humans than DBUs. 
```

2023-08-28 17:37 UTC, dralabeing approved these changes
LGTM

2023-08-29 05:28 UTC, luarss commented
@vvbandeira Fixed merge conflict

2023-08-29 11:30 UTC, vvbandeira approved these changes

2023-08-29 11:30 UTC, merged