Add check for no vias defined to avoid segmentation fault
The-OpenROAD-Project/OpenROAD pull request #3917
Opened 2023-08-28 11:36 UTC by refaay

2023-08-28 16:29 UTC, osamahammad21 requested changes

2023-08-28 16:29 UTC, osamahammad21 commented on src/drt/src/io/io_parser_helper.cpp
> +      if (layerNum >= BOTTOM_ROUTING_LAYER)
@refaay please resolve. Everything else looks fine to me.

2023-08-29 12:13 UTC, osamahammad21 approved these changes

2023-08-29 16:19 UTC, maliberty approved these changes

2023-08-29 16:19 UTC, merged