[Docs] OR review
The-OpenROAD-Project/OpenROAD pull request #4030
Opened 2023-09-22 17:21 UTC by luarss

According to the google [docs ](https://docs.google.com/document/d/1UQ-UbyEPy9UKQAtiVg6x9kPvOg-eeLFHYf_F6QHOhh0/edit)

Changes made:
- 1, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18

Changes in progress:
- 2, 3, 4, 5, 9, 10,

2023-10-17 17:13 UTC, dralabeing commented
@luarss Is this ready for review?

2023-10-17 17:37 UTC, luarss commented
Yes ready

2023-10-18 19:49 UTC, dralabeing commented on docs/contrib/DeveloperGuide.md
>  - Static IR analyser ([psm](../main/src/psm/README.md))
Change to analyzer

2023-10-18 19:53 UTC, dralabeing requested changes
Changes look good..except for the marked

2023-10-19 01:35 UTC, luarss commented on docs/contrib/DeveloperGuide.md
>  - Static IR analyser ([psm](../main/src/psm/README.md))
Fixed.

2023-10-20 17:07 UTC, dralabeing approved these changes

2023-10-21 07:13 UTC, luarss commented
The remaining changes 2-4 will be addressed in the next PR, since it involves creation of some new files. @dralabeing @vvbandeira 

We can merge this first.

2024-01-16 14:27 UTC, vvbandeira approved these changes

2024-01-16 14:28 UTC, merged