Change ripupMode to an enum
The-OpenROAD-Project/OpenROAD pull request #4135
Opened 2023-10-16 16:38 UTC by refaay

2023-10-16 17:51 UTC, rovinski commented on src/drt/src/TritonRoute.cpp
> +  }
This code is used twice; you can wrap it in a function.

2023-10-16 17:51 UTC, rovinski commented on src/drt/src/frBaseTypes.h
> +  ripupAroundDRC = 2
If the value is already part of the `RipUpMode` enum, I think it's a bit redundant to include `ripup` in the value name. e.g.
```
  UNKNOWN = -1,
  DRC = 0,
  ALL = 1,
  AROUND_DRC = 2
```

I think the style guidelines also prefer enums to be all capital letters.
Then the value would simply be e.g. `RipUpMode::DRC`

2023-10-16 17:51 UTC, rovinski commented on src/drt/src/TritonRoute.cpp
> +      debug_->ripupMode = fr::RipUpMode::UNKNOWN;
Is it necessary to use the `fr::` namespace here and everywhere else? I think it doesn't need it if it's already in the fr namespace. If it does, I might recommend using an alias for simplicity.

2023-10-17 10:22 UTC, osamahammad21 requested changes

2023-10-17 10:22 UTC, osamahammad21 commented on src/drt/src/frBaseTypes.h
> +  UNKNOWN = -1,
why do we need this UNKNOWN value?

2023-10-17 10:22 UTC, osamahammad21 commented on src/drt/src/dr/FlexDR.cpp
> +    {7, -6, 64, 64 * shapeCost, 16 * MARKERCOST, 100 * shapeCost, 0.999, RipUpMode::DRC, false}  // 64
Could you add the needed indentation for the rip up mode so that they are all aligned? makes it easier to read.

2023-10-17 16:31 UTC, osamahammad21 approved these changes

2023-10-17 16:31 UTC, osamahammad21 commented on src/drt/src/gr/FlexGR.cpp
>        }
I don't think This should be the same RipUpModeENUM. No DRC in GR

2023-10-17 17:59 UTC, maliberty approved these changes

2023-10-17 17:59 UTC, merged