[Docs] OR Review 2
The-OpenROAD-Project/OpenROAD pull request #4159
Opened 2023-10-21 14:50 UTC by luarss

Target Changes
- Prioritize prebuilt > docker > local installation 
- Add OS support matrix 

Pending Changes
- EQY/SBY Support once bug fixed.
- OR Change 4 
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/29f2dd27-0286-4e20-847c-0334bdd24875)

2023-10-26 18:34 UTC, luarss commented
@vvbandeira @dralabeing Current prototype for tabs https://openroad--4159.org.readthedocs.build/en/4159/main/src/README.html

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/772f5619-eb1f-4a68-8529-acfd494fb76a)

2024-01-16 14:30 UTC, vvbandeira commented
@luarss, DCO is missing. Could you sign the commits so we can proceed?

2024-01-16 16:02 UTC, luarss commented
@vvbandeira Ready for review. The tabbed code table looks nicer now.
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/39641663/12f9f781-c4df-40b2-a707-cb96809c8b9c)

2024-01-17 17:18 UTC, vvbandeira commented on docs/user/Build.md
> +There are 3 methods for building OpenROAD (in order of recommendation): prebuilt binaries, docker images, and finally local build.
```suggestion
There are three methods for building OpenROAD (in order of recommendation): prebuilt binaries, docker images, and finally, local build.  
```

2024-01-17 17:18 UTC, vvbandeira commented on docs/user/Build.md
> +Courtesy of [Precision Innovations](https://precisioninno.com/), there are pre-built binaries
```suggestion
Courtesy of [Precision Innovations](https://precisioninno.com/), there are prebuilt binaries
```

2024-03-03 09:34 UTC, luarss commented
@vvbandeira Can this be merged?

2024-06-16 13:24 UTC, luarss commented
@maliberty May I ask if who is the active tool maintainer for `eqy`? Are there any docs that I can insert for this?

2024-07-23 12:34 UTC, vvbandeira requested changes

2024-07-23 12:36 UTC, vvbandeira approved these changes

2024-08-23 13:28 UTC, luarss commented
@vvbandeira Ready to merge?

2024-08-27 13:03 UTC, vvbandeira reviewed
Debian 10 is EOL

2024-08-27 13:36 UTC, merged