Grt: refactor critical nets percentage information
The-OpenROAD-Project/OpenROAD pull request #4220
Opened 2023-11-06 21:35 UTC by arthurjolo

During the discussions on issue [#4121](https://github.com/The-OpenROAD-Project/OpenROAD/issues/4121) ,it was realized that the information of critical nets percentage was stored twice, some times creating a difference on the values stored. This branch moves to be stored only on fastroute.

2023-11-06 21:38 UTC, arthurjolo commented
This branch has passed throw a secure-CI, public designs are OK, but private designs need to check by someone with access.

2023-11-06 21:39 UTC, maliberty commented
You should get an email once the private designs finish with a summary.

2023-11-06 21:40 UTC, eder-matheus commented
> This branch has passed throw a secure-CI, public designs are OK, but private designs need to be check by someone with access.

Could you share the secure- branch name? Also, fix clang-format.

2023-11-06 21:41 UTC, maliberty commented
All designs that have finished so far have passed but a few big ones are still running.

2023-11-06 21:41 UTC, arthurjolo commented
> > This branch has passed throw a secure-CI, public designs are OK, but private designs need to be check by someone with access.
> 
> Could you share the secure- branch name? Also, fix clang-format.

Just fixed the clang-format, and the branch name is: secure-grt_refactor_cn_percentage

2023-11-07 02:53 UTC, eder-matheus requested changes
Just small requests, but this is almost ready to merge. I can see that secure-ci is almost done, and metrics are green for every design.

2023-11-07 02:53 UTC, eder-matheus commented on src/grt/src/GlobalRouter.cpp
>          "Timing is not available, setting critical nets percentage to 0");
Not related to your PR, but please add a period at the end of this sentence.

2023-11-07 02:53 UTC, eder-matheus commented on src/grt/src/GlobalRouter.cpp
> +        "Timing is not available, setting critical nets percentage to 0");
Same here. Add the period at the end.

2023-11-07 15:52 UTC, eder-matheus approved these changes

2023-11-07 17:11 UTC, eder-matheus commented
@arthurjolo The ok files of GRT unit tests need to be updated.

2023-11-07 20:04 UTC, merged