create and handle level shifters
The-OpenROAD-Project/OpenROAD pull request #4265
Opened 2023-11-14 16:55 UTC by ahmadelrouby

- Created ODB structure for UPF Level Shifters
- Added handler function for 'set_level_shifter' command in UPF to create and populate ODB with the appropriate data for level shifters
- Testing both update and create functionality

2023-11-14 21:12 UTC, QuantamHD commented
Looks like your generated odb files are out of date. https://github.com/The-OpenROAD-Project/OpenROAD/actions/runs/6868196432/job/18678191742?pr=4265

Try running the generate script again.

2023-11-15 05:14 UTC, maliberty requested changes

2023-11-15 05:14 UTC, maliberty commented on src/upf/src/upf.cpp
> +        odb::dbLevelShifter::create(block, name, pd));
why is a cast needed here?

2023-11-15 05:14 UTC, maliberty commented on src/upf/src/upf.cpp
> +      strcmp(use_functional_equivalence, "FALSE") ? true : false);
you might use strcasecmp to make it case insensitive

2023-11-15 05:14 UTC, maliberty commented on src/upf/src/upf.cpp
> +  ls->addExcludeElement(_exclude_element);
ls->addExcludeElement(exclude_element);
should work fine.

2023-11-15 05:14 UTC, maliberty commented on src/upf/src/upf.cpp
> +                                   char* exclude_element)
const

2023-11-15 05:14 UTC, maliberty commented on src/odb/src/db/dbLevelShifter.cpp
> +  // TODO
??

2023-11-18 21:45 UTC, ahmadelrouby commented on src/odb/src/db/dbLevelShifter.cpp
> +  // TODO
updated

2023-11-21 05:28 UTC, maliberty commented
Please fix 
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/79887244-a423-489d-b649-9e8526a274a0)

2023-11-21 05:29 UTC, maliberty commented
You should also merge master to pick up #4291

2023-12-01 00:34 UTC, maliberty commented
Please merge master and resolve the conflicts and this can go in.  Thanks for waiting.

2023-12-04 22:15 UTC, ahmadelrouby commented
@maliberty Should be okay now. Just need your approval.

2023-12-04 22:50 UTC, maliberty commented on src/odb/src/db/dbLevelShifter.cpp
> +void dbLevelShifter::setLocation(std::string location)
Can the code generator be told to take these by const & ?

2023-12-04 22:50 UTC, maliberty commented on src/odb/src/db/dbPowerDomain.cpp
> +  // User Code End >>
Could this be replaced by specifying 'schema' on the _levelshifters field in the schema?

2023-12-04 23:08 UTC, maliberty approved these changes
We'll save the code gen for another PR.

2023-12-04 23:08 UTC, merged

2023-12-04 23:09 UTC, maliberty commented
@fgaray FYI on another schema change