ppl: log enhancements
The-OpenROAD-Project/OpenROAD pull request #4338
Opened 2023-12-04 19:23 UTC by eder-matheus

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4314
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4208

2023-12-04 19:45 UTC, maliberty requested changes

2023-12-04 19:45 UTC, maliberty commented on src/ppl/src/IOPlacer.cpp
> +int IOPlacer::computeRegionIncrease(const Interval& interval, int num_pins)
Use const where possible.

2023-12-04 19:45 UTC, maliberty commented on src/ppl/src/IOPlacer.cpp
> +      = interval.getEdge() == Edge::top || interval.getEdge() == Edge::bottom;
Do you mean the pins are vertical?  The edges themselves are horizontal.  Similarly in IOPlacer::findSlots

2023-12-06 13:20 UTC, eder-matheus commented
@maliberty Any other comments for this PR?

2023-12-06 16:17 UTC, merged