gpl: Fix finding and replacing pins in clustering
The-OpenROAD-Project/OpenROAD pull request #4538
Opened 2024-01-15 23:09 UTC by therealshreyas

2024-01-16 06:35 UTC, maliberty commented
Please write a summary of this change ('fix' is too brief).

2024-01-16 07:25 UTC, therealshreyas commented
> Please write a summary of this change ('fix' is too brief).

Done!

2024-01-25 17:58 UTC, maliberty commented
Have you run asap7/aes-mbff with this change?

2024-01-25 18:00 UTC, maliberty requested changes

2024-01-29 19:57 UTC, therealshreyas commented on src/gpl/test/SingleBit/asap7sc7p5t_SEQ_LVT_TT_nldm_220123.lib
It has test_cell (+ I need LVT for sensible power ratio calculation)

2024-01-29 19:57 UTC, therealshreyas commented on src/gpl/test/SingleBit/asap7sc7p5t_SEQ_RVT_FF_nldm_220123.lib
It has test_cell

2024-01-29 20:01 UTC, therealshreyas commented on src/gpl/test/clust03.tcl
clust01 and clust02 provide enough coverage (varying alpha, split_size, and input size)

2024-01-29 21:13 UTC, therealshreyas commented on src/gpl/test/SingleBit/asap7sc7p5t_28_L_1x_220121a.lef
No (R / L difference)

2024-02-02 05:58 UTC, maliberty approved these changes

2024-02-02 05:58 UTC, merged