odb: add MASK support for special nets
The-OpenROAD-Project/OpenROAD pull request #4556
Opened 2024-01-19 16:28 UTC by gadfort

Adds:
- DEFin and DEFout support for MASK for both VIA and LAYER in Special nets + added to CI testing for read_def58 and write_def58

Fixes:
- Ensure dbWireShapeType is initialized in the `const char*` constructor
- Fixes reading of RECTs in DEFin for special nets to preserve their TYPE and SHAPETYPE (+ CI check for this)

2024-01-19 19:36 UTC, QuantamHD requested changes

2024-01-19 19:36 UTC, QuantamHD commented on src/odb/src/defin/definSNet.cpp
> +                                    0,
Any time you have constants like these it's good to append the param name as a block comment.

```c++
/*x=*/ 0,
/*y=*/ 0,
/*z=*/ 0,

```

2024-01-19 19:36 UTC, QuantamHD commented on src/odb/src/defin/definSNet.cpp
> +                                    0,
Param names as comments

2024-01-19 21:04 UTC, maliberty commented on src/odb/src/db/dbBox.cpp
> -  }
should this be in _dbBox::checkMask ?

2024-01-19 21:04 UTC, QuantamHD approved these changes

2024-01-19 21:05 UTC, maliberty commented on src/odb/src/db/dbSBox.h
> +  uint _spare_bits : 18;
I don't think you actually need to rev the schema and add this backward compatibility as you are just converting spare bits to used.  The spare bits are 0 already in old dbs.

2024-01-20 15:08 UTC, gadfort commented on src/odb/src/db/dbBox.cpp
> -  }
got lost in the shuffle, restored now.

2024-01-22 04:34 UTC, maliberty approved these changes

2024-01-22 04:34 UTC, merged