Grt: Fixing the overlapped edges after maze3D
The-OpenROAD-Project/OpenROAD pull request #4606
Opened 2024-01-30 17:29 UTC by luis201420

Fixing overlapping edges generated after the maze3D function

2024-01-30 17:33 UTC, maliberty commented
Have you run a secure CI?

2024-01-31 19:01 UTC, eder-matheus requested changes
Before any other changes I requested, please resolve the failures in the unit tests. It's important to have the unit tests working to ensure that your further changes will not break anything.

2024-02-05 14:00 UTC, eder-matheus approved these changes
Just address my final comment before merging.
I see CI is passing.

2024-02-05 14:00 UTC, eder-matheus commented on src/grt/src/fastroute/include/FastRoute.h
> +  void addNbrPoints(int netID,
Avoid abbreviations in the function names. Change `addNbrPoints` to `addNeighborPoints`.

2024-02-05 18:05 UTC, merged