ubi9 dep
The-OpenROAD-Project/OpenROAD pull request #4846
Opened 2024-03-24 00:47 UTC by habibayassin

2024-04-01 18:16 UTC, vvbandeira requested changes

2024-04-01 18:16 UTC, vvbandeira commented on etc/DependencyInstaller.sh
> +#         if [[ $(yum repolist | egrep -c "rhel-8-for-x86_64-appstream-rpms") -eq 0 ]]; then
Remove

2024-04-01 18:53 UTC, vvbandeira commented on etc/DependencyInstaller.sh
> +#         if [[ $(yum repolist | egrep -c "rhel-8-for-x86_64-appstream-rpms") -eq 0 ]]; then
Also, there's a merge conflict now.

2024-04-24 15:57 UTC, vvbandeira requested changes
We need a version check as we do for Ubuntu to ensure we do not try to install the packages on an unsupported version.

2024-04-30 06:14 UTC, rovinski commented on etc/DependencyInstaller.sh
> +            echo "ERROR: RHEL 9 is only supported" >&2
```suggestion
            echo "[ERROR] Only version 9 of RHEL supported" >&2
```

2024-11-21 13:36 UTC, closed without merging