grt: add vias when computing obstructions from nets
The-OpenROAD-Project/OpenROAD pull request #4924
Opened 2024-04-08 20:21 UTC by eder-matheus

2024-04-08 22:08 UTC, maliberty requested changes

2024-04-08 22:08 UTC, maliberty commented on src/grt/src/GlobalRouter.cpp
> +            odb::dbTechLayer* tech_layer = shape.getTechLayer();
This isn't right as it is for a segment not a via.  I think you want getViaBoxes.

2024-04-09 03:55 UTC, maliberty approved these changes
The code looks fine but I suggest a secure CI

2024-04-09 04:01 UTC, maliberty commented
I started a secure CI for you (secure-grt_vias)

2024-04-09 17:04 UTC, eder-matheus commented
PR https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1924 created to fix CI failures.

2024-04-09 20:10 UTC, merged