Odb: user derating relocation
The-OpenROAD-Project/OpenROAD pull request #4944
Opened 2024-04-12 22:19 UTC by gudeh

Bringing back this modification, since it showed necessary. RUDY requires some way to load the user derating without overwriting the GRT information, now that it is shared. For that we opted to put the user layer adjustment in ODB, in dbTechLayer. The code generator was used to do so.

2024-04-12 22:56 UTC, eder-matheus requested changes

2024-04-12 22:56 UTC, eder-matheus commented on src/grt/src/GlobalRouter.cpp
> +    if (db_->getTech()->findRoutingLayer(l)->getLayerAdjustment() == 0.0) {
Refactor this long function calls:
```
odb::dbTechLayer* tech_layer = getTech()->findRoutingLayer(l);
tech_layer->getLayerAdjustment()
```

And use the tech_layer in the lines below.

2024-04-12 22:56 UTC, eder-matheus commented on src/grt/src/GlobalRouter.cpp
> +    float adjustment
Same here. Even if you only use it once, I think it's good to separate it for readability.

2024-04-13 01:06 UTC, rovinski commented
Would be a good idea to rebase this PR to avoid the spurious changes.

2024-04-15 18:25 UTC, closed without merging

2024-04-15 19:10 UTC, gudeh commented
Closed due to too many unnecessary commits and failed rebase.