Ant: new implementation using boost polygon
The-OpenROAD-Project/OpenROAD pull request #5098
Opened 2024-05-13 23:17 UTC by luis201420

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3892
I ran a secure-ci with only the public designs, I'm waiting for the results

2024-05-13 23:20 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +//#include <boost/polygon/polygon.hpp>
Remove commented code if it's useless.

2024-05-13 23:51 UTC, eder-matheus requested changes

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +struct InfoType
`InfoType` is too generic. What would you like to express here? The violation itself, the data computed for each gate?

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +typedef std::unordered_map<dbTechLayer*, InfoType> LayerInfoVector;
Similar question here. What is LayerInfo? Info is a bad name because it says nothing about what it represents in the code.

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +  std::unordered_map<std::string, LayerInfoVector> info_;
Change `info_` for a more meaningful name.

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +  bool dsu_same(int u, int v);
Function names should always use camel case.
```
init_dsu(); --> initDsu
find_set(int v); --> findSet
union_set(int u, int v); --> unionSet
dsu_same(int u, int v); --> dsuSame
```

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +  vector<Violation> getAntennaViolations2(dbNet* net,
After finishing the reviews, I believe we will deprecate the old code, so we'll not have two functions with the same name.
@maliberty do you think we should completely remove the old code?

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +  int checkInfo(dbNet* db_net,
Change `checkInfo` for a more meaningful name (related to the comments about InfoType being a bad struct name).

2024-05-13 23:51 UTC, eder-matheus commented on src/ant/src/AntennaChecker.cc
> +using odb::dbWirePathShape;
Why are these added? Remove if you don't need to use it.

2024-05-13 23:53 UTC, eder-matheus commented
@luis201420 you will need to update the repair_antennas unit tests and the ant unit tests ok files.

2024-05-16 17:11 UTC, luis201420 commented
> @luis201420 you will need to update the repair_antennas unit tests and the ant unit tests ok files.

I'm going to update it, I'm checking the differences in the unit tests.

2024-06-04 15:16 UTC, eder-matheus commented
Secure-ci is running with the latest updates. If everything passes, this PR should be ready to merge.

2024-06-05 13:54 UTC, eder-matheus commented
@vvbandeira This is ready to merge.

2024-06-05 14:05 UTC, merged