Dpl: Inserting decap cells with the insert_decap command
The-OpenROAD-Project/OpenROAD pull request #5316
Opened 2024-07-01 20:26 UTC by luis201420

Creating the `insert_decap` command to insert decap cells in the areas with the highest IR DROP.
To use the command you must first execute `analyze_power_grid` for the net VDD, to obtain the areas with the highest IR DROP.
Fixes #4970

2024-07-01 21:04 UTC, eder-matheus requested changes
Could you also add a small unit test?

2024-07-01 21:04 UTC, eder-matheus commented on src/dpl/src/Opendp.i
> +set_decap_master(odb::dbMaster *master, float cap)
add_decap_master

2024-07-01 21:04 UTC, eder-matheus commented on src/dpl/src/Opendp.tcl
> +sta::define_cmd_args "insert_decap" { [-cap target] [-cells cell_info] }
Perhaps change `-cap` to `-target_cap`?

2024-07-01 21:28 UTC, maliberty commented on src/dpl/src/DecapPlacement.cpp
> +        DPL, 54, "Filler cells found when running insert decap cells");
More actionable: Run remove_fillers before inserting decap cells

2024-07-06 16:26 UTC, maliberty commented
@luis201420 do you have an ETA to resolve the feedback?

2024-07-12 17:55 UTC, luis201420 commented
Hi @maliberty,
I was investigating the compilation error. I can now reproduce the error, I think the difference in GNU version was the problem.
I tried first running the master branch without my modifications to verify that everything compiles without problems, then I added the `psm` to the `dpl` CMakeList file and compiled again. The latter resulted in the same problem that is had in Jenkins.
The cause is probably that, when placing `psm` in `dpl`, it needs `psm` to be compiled first, but also in `psm` it has dependencies like `rsz`, and `rsz` has dependencies like `grt` and `grt` has `dpl` as a dependency. Which will generate a loop in compilation.
Perhaps a possible solution is to place the command `insert_decap` in `psm`, to avoid adding `psm` in `dpl`. The idea would be to execute the command in `psm` and then using a `dpl` function to add the decap cells passing the IR DROPS as a parameter. (add `dpl` in `psm` instead of `psm` in `dpl`).
What do you think about it?

2024-07-17 16:04 UTC, eder-matheus commented on src/psm/include/psm/pdnsim.h
> +using odb::dbMaster;
@luis201420 You should move this inside the psm namespace.

2024-07-18 20:04 UTC, eder-matheus requested changes

2024-07-18 20:04 UTC, eder-matheus commented on src/psm/test/insert_decap1.tcl
> +#insert_decap -target_cap 1000.5 -cells {"sky130_fd_sc_hd__decap_3" 0.93 "sky130_fd_sc_hd__decap_4" 1.24 "sky130_fd_sc_hd__decap_6" 1.86 "sky130_fd_sc_hd__decap_8" 2.48 "sky130_fd_sc_hd__decap_12" 3.
Remove the commented code.

2024-07-18 20:33 UTC, maliberty commented on src/psm/src/pdnsim.tcl
> +  puts $net_name
rm ?

2024-07-18 22:11 UTC, maliberty commented
@eder-matheus I have no further comments - I'll leave it to you to comment or merge.

2024-07-18 22:22 UTC, eder-matheus approved these changes

2024-07-18 22:22 UTC, merged