gpl: modify log and readme for timing driven mode clarity
The-OpenROAD-Project/OpenROAD pull request #5318
Opened 2024-07-01 23:22 UTC by gudeh

Include more clear messages during timing driven mode so the user can better understand what is happening. 
Include possible actions for user to improve runtime due to slow timing driven mode.
Include new tcl command in README for using grt(previous) routing congestion estimator during routability.
Fix default inflation parameters in README.

2024-07-01 23:22 UTC, gudeh commented
These changes should address issue #5203.

2024-07-01 23:24 UTC, gudeh commented
I included the message "Timing-driven: executing resizer for reweighting nets." because the resizer may take a long time, this way the user can know why the tool is loading.

2024-07-01 23:25 UTC, maliberty commented
@oharboe please comment as it is your issue

2024-07-02 06:23 UTC, oharboe requested changes
Just a nit, see comments.

More general comments:

I think the main usability improvement here is that RUDY is used and that is adequately documented.

The other routing options require a strong mental model of what is going on. They are not "user-servicable parts" to my mind.

A user-servicable knob would be something like a value between 0 and 1 where 0 is fastest and 1 is best quality of results...

I'm not suggesting that such a feature should be implemented, but are interested in hearing thoughts.

I think the explanation of the "non user-servicable parts" of OpenROAD here are good.

2024-07-02 06:23 UTC, oharboe commented on src/gpl/README.md
> +long during routability-driven execution, consider raising the target RC value
as above. Reduce guesswork; be explicit about which option to use to "the target RC value".

2024-07-03 15:52 UTC, gudeh commented
I realized we do not have the number of buffers inserted (and other modifications by resizer) in the gpl log. Which makes sense because we do a virtual resizing. I will include this info in a new PR, since it is more related to issue #5291.

Do you think this modifications are good to go? @maliberty @oharboe

2024-07-03 15:55 UTC, oharboe approved these changes
This level of detail on global router is too deep for my current understanding, so I can't comment much.

2024-07-03 17:17 UTC, maliberty approved these changes

2024-07-03 17:17 UTC, merged

2024-07-03 17:18 UTC, maliberty commented
> I realized we do not have the number of buffers inserted (and other modifications by resizer) in the gpl log.

This may be better as a debugPrint as I'm not sure users will care.