GDS Reader & Writer in ODB
The-OpenROAD-Project/OpenROAD pull request #5555
Opened 2024-08-12 03:14 UTC by fangzhonglyu

Implement a GDS Reader and Writer in OpenRoad. Add ODB classes for GDS Structures and Elements

2024-08-12 21:14 UTC, QuantamHD commented on src/odb/include/odb/xml.h
Can this custom XML parser be replaced by boost property trees

https://gist.github.com/endJunction/4030890

2024-08-12 21:27 UTC, fangzhonglyu commented on src/odb/include/odb/xml.h
Didn't know that Boost had an XML parser, should be doable

2024-08-12 22:12 UTC, maliberty requested changes
All h/cpp need a copyright header

2024-08-12 22:12 UTC, maliberty commented on src/odb/src/codeGenerator/schema/gds/dbGDSText.json
> +        "name":"_pathType",
I don't think we need path_type for a text element (obsolete)

2024-08-12 22:12 UTC, maliberty commented on src/odb/src/codeGenerator/schema/gds/dbGDSText.json
> +        "name":"_sTrans",
naming: transform

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsin.h
> +  std::ifstream _file;
data members should come after methods (https://google.github.io/styleguide/cppguide.html#Declaration_Order)

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsin.h
> +   * Checks if the _r is the expected type
_r ?

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsout.h
> +class GDSWriter
gdsin.h has lots of nice comments - this is the poor cousin?

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsUtil.h
> +enum RecordType
Use "enum class" for better scoping.

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsUtil.h
> +enum DataType
enum class

2024-08-12 22:12 UTC, maliberty commented on src/odb/include/odb/gdsUtil.h
Does this header need to be public?  It doesn't seem like it would be useful outside of odb.

2024-08-12 22:12 UTC, maliberty commented on src/odb/src/gdsin/xml.h
> +#include "odb/xml.h"
Why have a header just to include another?

2024-08-13 13:35 UTC, maliberty commented
@oharboe note that the gds today is generated by klayout so this would help only for future work.

2024-08-13 13:39 UTC, oharboe commented
> @oharboe note that the gds today is generated by klayout so this would help only for future work.

For my part reproducible .gds and .spef files is into the future anyway, so waiting for .gds writing directly from .odb is OK as it reduces the totalt engineering effort.

Is klayout *only* used to write .gds files and will klayout be dropped after .odb to .gds writes is activated in ORFS?

2024-08-13 13:43 UTC, maliberty commented
In some PDKs klayout could be used for DRC checking.  It will likely be a while until OR can generate GDS as this is just a first step.

2024-08-14 00:17 UTC, fangzhonglyu commented
> @fangzhonglyu do you plan to handle aref?

Yes, AREF is already built into the reader/writer and shares the same class as SREF

2024-08-14 18:37 UTC, maliberty commented
@fangzhonglyu please ping when you have addressed all the feedback and this is ready for re-review.

2024-08-21 23:35 UTC, fangzhonglyu commented on src/odb/include/odb/gdsUtil.h
Mostly there for the tests to access

2024-08-24 18:10 UTC, fangzhonglyu commented on src/odb/include/odb/xml.h
This is replaced now.

2024-09-03 20:31 UTC, fangzhonglyu commented
@maliberty I believe everything is fixed?

2024-09-03 22:01 UTC, fangzhonglyu commented on SKY130.lyp
Just removed that, it probably sneaked in there when I was testing the layer parser

2024-09-04 04:34 UTC, maliberty approved these changes

2024-09-04 04:36 UTC, merged