Grt: Jumper insertion for repair antenna violations
The-OpenROAD-Project/OpenROAD pull request #5784
Opened 2024-09-20 23:28 UTC by luis201420

### Jumper insertion for repair antenna violations
The algorithm adds jumpers with size = 3GCells in the long segments with antenna violations.

- First it verifies that the layer has available layers above it with the same orientation (layer level + 2)
- The net segments are structured to be able to obtain the segments involved in each antenna violation. For this, the DSU algorithm is used.
- With the segments found, the bounding box is found and the number of pins near the min and max points of the bounding box is calculated. This will help to find the segment to insert the jumpers.
- To o find the position where a jumper should be added, the algorithm will calculate a ratio of the current PAR to the required PAR. To use the ratio it divides the total wirelength of the segments by the ratio, to get the required wirelength which will not have a violation.
- To insert the jumpers, the segments are iterated looking for the position that can contain the jumper size avoiding adding over vias. Before inserting the jumper, it is verified that the layer has the necessary resources for its jumper routing.
- When an antenna violation has pins near both sides, two jumpers will be inserted near both ends.

2024-09-27 19:23 UTC, eder-matheus requested changes
This is the first batch of reviews. I'll wait for the changes before finishing the review of the last functions.

2024-09-27 19:23 UTC, eder-matheus commented on src/grt/src/RepairAntennas.cpp
> +    // if seg could have jumper, get via position
This comment seem out of place. I can't find in the code where you're getting the via position.

2024-09-27 19:23 UTC, eder-matheus commented on src/grt/src/RepairAntennas.cpp
> +      // if is valid segment, save the segment pos in route
Same here. I don't understand the "save the segment pos in route".

2024-09-27 19:23 UTC, eder-matheus commented on src/grt/src/RepairAntennas.cpp
> +    }
This block of code is almost identical to the block above. Could you refactor it into a single function?

2024-09-27 19:23 UTC, eder-matheus commented on src/grt/src/RepairAntennas.cpp
> +void RepairAntennas::getPinNumberNearEndPoint(
getPinNumberNearEndPoint --> getPinCountNearEndPoints

2024-09-27 19:23 UTC, eder-matheus commented on src/grt/src/RepairAntennas.cpp
> +struct SegInfo
Why do you have a struct definition here? Should this be moved to the header?

2024-09-27 19:58 UTC, luis201420 commented on src/grt/src/RepairAntennas.h
> +struct ViolationInfo
Yes, the members refer to the pin count near the start and the end of the segments

2024-09-27 20:09 UTC, luis201420 commented on src/grt/src/RepairAntennas.cpp
> +bool validatePos(bool is_reversed,
Yes, this function helps me verify that the position is within the segment. It helps me validate the position in the while loop.

2024-09-27 20:27 UTC, eder-matheus commented on src/grt/src/RepairAntennas.h
> +struct ViolationInfo
Please rename the struct name to be more related to its members. `ViolationInfo` says nothing about it.

2024-10-01 21:03 UTC, eder-matheus requested changes

2024-10-09 14:39 UTC, eder-matheus approved these changes

2024-10-09 14:39 UTC, merged

2024-10-23 17:11 UTC, rovinski commented on src/grt/src/RepairAntennas.cpp
> +    const odb::Point gate_maxX_maxY(sink_bbox.xMax(), sink_bbox.yMax());
`Rect.ll()`, `Rect.ur()`, etc?