drt: elimination of dupicate code on genAPsFromRect
The-OpenROAD-Project/OpenROAD pull request #5803
Opened 2024-09-25 19:07 UTC by bnmfw

genAPsFromRect has a lot of code duplication. 
### Problem:
When generating access points for a given rectangle shape there are two relevant layer, a layer 1 and layer 2. The code verified if layer 1 was horizontal. If true it made a bunch of calls to generate access points. In some cases Y/vertical coordinates were used and other X/horizontal coordinates were used. If false it made the exact functions calls with the same patterns, except Y/vertical and X/horizontal were switched. This happened twice.
### Solution:
Auxiliary variables `layer1_rect_min`, `layer1_rect_max`, `layer2_rect_min`, `layer2_rect_max`, `layer1_coords` and `layer2_coords` were created. The logic to check if layer 1 is horizontal is done in them through ternary operations and they are used in posterior calls, so code does not have to be duplicated

2024-09-25 19:07 UTC, bnmfw commented
@joaomai this is the PR Eder just mentioned on today's meeting

2024-09-26 01:44 UTC, maliberty requested changes

2024-09-26 01:44 UTC, maliberty commented on src/drt/src/pa/FlexPA_prep.cpp
> +  int layer2_rect_max = is_layer1_horz ? gtl::xh(rect) : gtl::yh(rect);
const

2024-09-26 01:44 UTC, maliberty commented on src/drt/src/pa/FlexPA_prep.cpp
> +      = is_layer1_horz ? x_coords : y_coords;
I think `auto& layer1_coords = is_layer1_horz ? y_coords : x_coords;` reads easier here as the type is not what's important.  Likewise layer2.

2024-09-26 01:44 UTC, maliberty commented on src/drt/src/pa/FlexPA_prep.cpp
> +    lower_type = frAccessPointEnum::OnGrid;
There is an odd asymmetry to this line.  It only appears in one of the four branches.  I think this PR moves it into two of the branches.  I'm not sure it belongs in any.

2024-09-26 20:24 UTC, maliberty commented
Ok with me; I'll leave a chance for @osamahammad21 to comment (and merge when satisfied).

2024-09-30 15:23 UTC, merged