drt: Push node index computation up
The-OpenROAD-Project/OpenROAD pull request #5913
Opened 2024-10-10 13:48 UTC by kbieganski

No functional change intended. This speeds up DRT by 3-8%, at least for `asap7` (varies depending on the design). Baseline is a recent commit from Oct 6.

## `asap7/aes` - stage `5_2_route` - 8 thread(s)

| Branch | Min [s] | Median [s] | Relative |
|--------|---------|------------|----------|
| Baseline | 221.96 | 222.23 | 1.03 |
| This PR | 215.48 | 215.91 | 1.00 |

## `asap7/ibex` - stage `5_2_route` - 8 thread(s)

| Branch | Min [s] | Median [s] | Relative |
|--------|---------|------------|----------|
| Baseline | 337.61 | 338.30 | 1.08 |
| This PR | 312.99 | 313.16 | 1.00 |

2024-11-14 14:00 UTC, kbieganski commented
@osamahammad21 Have you had a change to look at this?

2025-01-03 19:29 UTC, kbieganski commented
Can this be reviewed?

2025-01-04 05:51 UTC, maliberty commented
@osamahammad21 please review

2025-01-06 16:48 UTC, osamahammad21 requested changes
In this PR, I see that checking for an index validity is completely removed from all APIs. Has it been verified that the passed index to getIdx is valid? For example, bi.z() - 1 could be -1 in some cases, right?

2025-01-07 21:30 UTC, kbieganski commented
I think each `switch` is a mix of checked and unchecked accesses (the `*Fixed*` ones are checked, the `*Route*` ones aren't). For example, see [this part](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5913/files#diff-3b0ee5af511f4838323555d94ad93cc7da9df71a64bf049fa6b634da77978e64L84-R85) which calls [this function](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5913/files#diff-a62f2dab4026966036f9855039c60b6de4b6f462499a04b0043890390288d668L555-R558). So I was confused by the "safe access" comment, thought it was about something else. Anyway, it seems the checks aren't actually needed?

2025-01-14 11:21 UTC, kbieganski commented
@osamahammad21 In case you missed it

2025-01-14 14:10 UTC, osamahammad21 commented
Sorry I didn't notice your comment. It seems that as you said we do not always check the validity of the index which is kind doesn't seem very safe. However, this PR doesn't introduce new problems, So I'll just merge and get back to the index validity later on a separate PR.

2025-01-14 14:10 UTC, osamahammad21 approved these changes

2025-01-14 14:10 UTC, merged