dpl: add verbose flag to filler_placement to print filler cell usage
The-OpenROAD-Project/OpenROAD pull request #6280
Opened 2024-12-01 17:01 UTC by gadfort

2024-12-01 23:00 UTC, maliberty requested changes
This is similar to dbSta::report_cell_usage - perhaps there is some sharing possible?

2024-12-01 23:43 UTC, gadfort commented on src/dpl/test/regression_tests.tcl
> +  fillers9_verbose
When are we retiring the two lists?

2024-12-02 00:05 UTC, gadfort commented
@maliberty Not sure what sharing would make sense but we can explore that as a separate issue.

2024-12-02 03:33 UTC, maliberty approved these changes

2024-12-02 03:34 UTC, maliberty commented on src/dpl/test/regression_tests.tcl
> +  fillers9_verbose
When someone gets around to making the flow tests work from ctest as well.

2024-12-02 11:00 UTC, merged