drt: last name changes and doxygen
The-OpenROAD-Project/OpenROAD pull request #6359
Opened 2024-12-16 06:09 UTC by bnmfw

Fixes #5721. Finally.

This PR is only aesthetic, it only adds missing Doxygen documentations to most functions on the PA module and changes some names. Some functions, specially on the row_patters and acc_patterns files were left simple as the high level view of both files is pretty straight forward, acc_point is the elaborate one.

Ignoring function name changes to camelCase here are all function name changes, I find they describe the function better (filter describes what is happening way better than check or add). Here are they:

- `initAllAccessPoints` → `genAllAccessPoints`
- `gen_createAccessPoint` → `createSingleAccessPoint`
- `gen_initializeAccessPoints` → `createMultipleAccessPoints`
- `check_addPlanarAccess` → `filterPlanarAccess`
- `check_addViaAccess` → `filterViaAccess`
- `checkViaAccess` → `checkViaPlanarAccess`
- `check_addAccess` → `filterSingleAPAccesses`
- `check_setAPsAccesses` → `filterMultipleAPAccesses`
- `initPinAccessCostBounded` → `genPinAccessCostBounded`
- `initPinAccess` → `genPinAccess`
- `initInstAccessPoints` → `genInstAccessPoints`
- `initAllAccessPoints` → `genAllAccessPoints`

2024-12-16 06:35 UTC, rovinski commented on src/drt/src/pa/FlexPA.h
> +   * @brief initializes the nodes data strucutes that will be used to solve the
```suggestion
   * @brief initializes the nodes' data structures that will be used to solve the
```

2024-12-16 06:35 UTC, rovinski commented on src/drt/src/pa/FlexPA.h
> +   * @brief resets the nodes data strucutes that will be used to solve the
```suggestion
   * @brief resets the nodes' data structures that will be used to solve the
```

2024-12-16 06:35 UTC, rovinski commented on src/drt/src/pa/FlexPA.h
> +   * @param isPrev wether this is the previous or current node
```suggestion
   * @param isPrev whether this is the previous or current node
```

2024-12-22 12:32 UTC, osamahammad21 requested changes

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @param high_cost access cost of the upper layer
?

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @param upper_type upper layer cost
types

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +                               frAccessPointEnum high_cost);
Stick with type as they are actually types not costs.

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @brief adjusts the coordinates for all access points
```suggestion
   * @brief Adjusts the coordinates for all access points
```

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @brief resets the nodes' data structures that will be used to solve the
```suggestion
   * @brief Resets the nodes' data structures that will be used to solve the
```

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @brief initializes the nodes' data structures that will be used to solve
```suggestion
   * @brief Initializes the nodes' data structures that will be used to solve
```

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @brief Another auxilary function for debugging
```suggestion
   * @brief Auxilary function for debugging
```

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   * @brief checks for any DRVs.
```suggestion
   * @brief Checks for any DRVs.
```

2024-12-22 12:32 UTC, osamahammad21 commented on src/drt/src/pa/FlexPA.h
> +   */
Returns true or false if there are DRVs?

2025-01-07 19:22 UTC, osamahammad21 approved these changes

2025-01-07 19:22 UTC, merged