ant: fixing data races
The-OpenROAD-Project/OpenROAD pull request #6364
Opened 2024-12-16 23:57 UTC by luis201420

This PR fixes data races found by ThreadSanitizer in ANT.  It is caused by the `net_to_report_` shared variable. 
The modifications made are:
- Adding mutex to protect access to the map.
- Removing unused parameters in functions.

2024-12-17 13:33 UTC, eder-matheus commented
@luis201420 Please look at the failures in the CI. The regression tests are crashing.

2024-12-17 13:37 UTC, eder-matheus requested changes

2024-12-17 13:37 UTC, eder-matheus commented on src/ant/include/ant/AntennaChecker.hh
> +  std::mutex mapMutex;
Class members should follow the same name pattern: map_mutex_

2024-12-18 16:53 UTC, eder-matheus approved these changes

2024-12-20 01:49 UTC, luis201420 commented
The latest changes address and resolve all the issues identified by ThreadSanitizer.

2024-12-20 13:19 UTC, eder-matheus commented on src/ant/src/AntennaChecker.cc
> +  std::lock_guard<std::mutex> lock(map_mutex_);
Why is this needed? writeReport doesn't run in multithread.

2024-12-20 13:19 UTC, eder-matheus commented on src/ant/src/AntennaChecker.cc
> +  std::lock_guard<std::mutex> lock(map_mutex_);
Same question here. printReport is only called inside checkAntennas, out of a multithread region of the code.

2024-12-20 16:36 UTC, eder-matheus approved these changes

2024-12-20 16:36 UTC, merged