mpl2: new flags for individual manual macro placement
The-OpenROAD-Project/OpenROAD pull request #6403
Opened 2024-12-20 20:37 UTC by AcKoucher

Resolve #6385 

Added:

| Flag | Behavior |
| ----- | ----- |
| -dont_snap | Enforce location set |
| -check_overlap | Only places macro if no overlap is found |

2024-12-20 20:51 UTC, AcKoucher commented
@oharboe I thought perhaps `-literal` could be a bit confusing when using both flags at the same time, so I decided to go with more somewhat straightforward names.

2024-12-20 20:58 UTC, oharboe requested changes
I suggest using positive names, easier to document and reason about and to check default to check for overlap

2024-12-20 20:58 UTC, oharboe commented on src/mpl2/src/mpl.tcl
> +                                    [-dont_snap]
I find negative names to cause more confusion and be harder to discuss in documentation and harder to remember. I would prefer a positive name, like `-exact` as in exact coordinates.

2024-12-20 20:58 UTC, oharboe commented on src/mpl2/README.md
> +| `-check_overlap` | Place macro only if no overlap with other macros is found. |
I think this should be default and also to have a positve name, so how about `-allow_overlap`?

2024-12-20 21:17 UTC, oharboe approved these changes
😌

2024-12-22 18:36 UTC, eder-matheus approved these changes

2024-12-23 15:41 UTC, merged