Update GettingStarted.rst
The-OpenROAD-Project/OpenROAD pull request #712
Opened 2021-06-07 21:03 UTC by dralabeing

Corrected the path name to the design make file to use config.mk under Designs

2021-06-07 21:06 UTC, maliberty approved these changes

2021-06-08 07:10 UTC, rovinski requested changes

2021-06-08 07:10 UTC, rovinski commented on docs/user/GettingStarted.rst
> +``make DESIGN_CONFIG=./designs/nangate45/swerve/config.mk`` or
It's "swerv" not "swerve"

2021-06-08 15:34 UTC, dralabeing commented
Thanks...will fix

On Tue, 8 Jun 2021 at 00:10, Austin Rovinski ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/user/GettingStarted.rst
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/712#discussion_r647171887>
> :
>
> > @@ -79,8 +79,8 @@ You can select a design using either of the following methods:
>  1. The flow `Makefile`_ contains a list of sample design configurations at
>  the top of the file.  Uncomment the respective line to select the design
>  2. Specify the design using the shell environment, e.g.
> -``make DESIGN_CONFIG=./designs/nangate45/swerv.mk`` or
> -``export DESIGN_CONFIG=./designs/nangate45/swerv.mk ; make``
> +``make DESIGN_CONFIG=./designs/nangate45/swerve/config.mk`` or
>
> It's "swerv" not "swerve"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/712#pullrequestreview-678163181>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUHA6L56LSENAXJ62KERV6TTRW67PANCNFSM46IPABRA>
> .
>

2021-06-08 15:49 UTC, dralabeing commented
I just created a new pull request with this fix- is there a way to modify
and use original pull request? Just checking on the correct procedure...
thanks

On Tue, 8 Jun 2021 at 08:34, Indira Iyer ***@***.***> wrote:

> Thanks...will fix
>
> On Tue, 8 Jun 2021 at 00:10, Austin Rovinski ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In docs/user/GettingStarted.rst
>> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/712#discussion_r647171887>
>> :
>>
>> > @@ -79,8 +79,8 @@ You can select a design using either of the following methods:
>>  1. The flow `Makefile`_ contains a list of sample design configurations at
>>  the top of the file.  Uncomment the respective line to select the design
>>  2. Specify the design using the shell environment, e.g.
>> -``make DESIGN_CONFIG=./designs/nangate45/swerv.mk`` or
>> -``export DESIGN_CONFIG=./designs/nangate45/swerv.mk ; make``
>> +``make DESIGN_CONFIG=./designs/nangate45/swerve/config.mk`` or
>>
>> It's "swerv" not "swerve"
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/712#pullrequestreview-678163181>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AUHA6L56LSENAXJ62KERV6TTRW67PANCNFSM46IPABRA>
>> .
>>
>

2021-06-08 16:10 UTC, maliberty commented
If you just push to the same branch the PR will update.

2021-06-08 17:20 UTC, dralabeing commented
Thanks Matt...fixed

2021-06-08 21:21 UTC, rovinski commented
@dralabeing you can see at the top of this PR that it was opened from branch `patch-2`. You need to push to that specific branch to update this PR, not create a new branch.

2021-06-09 04:15 UTC, dralabeing commented on docs/user/GettingStarted.rst
> +``make DESIGN_CONFIG=./designs/nangate45/swerve/config.mk`` or
Fixed swerve to swerv

2021-06-09 04:17 UTC, dralabeing commented
Thanks  Austin.. new to GitHub.. I think I got it right this time

On Tue, 8 Jun 2021 at 14:21, Austin Rovinski ***@***.***>
wrote:

> @dralabeing <https://github.com/dralabeing> you can see at the top of
> this PR that it was opened from branch patch-2. You need to push to that
> specific branch to update this PR, not create a new branch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/OpenROAD/pull/712#issuecomment-857163119>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUHA6L2FAOD2RGKO2PJN42TTR2CWFANCNFSM46IPABRA>
> .
>

2021-06-09 05:13 UTC, merged