grt: fix congestion issues
The-OpenROAD-Project/OpenROAD pull request #794
Opened 2021-06-25 22:34 UTC by eder-matheus

- Added check for huge usage values in 2D edges
- Added limitation to the number of total overflow increases during overflow iterations
- Overflow in the final routing is allowed now
- Four unit tests for congestion, including a case that tries to replicate the issue in [OR-1032](https://openroad.atlassian.net/browse/OR-1032)

2021-06-26 03:11 UTC, maliberty requested changes
Why are we allowing routing to end with overflow by default?  We will be passing an infeasible solution onto detailed routing which will likely fail too.

2021-06-26 03:11 UTC, maliberty commented on src/grt/src/fastroute/src/utility.cpp
> +                      "Horizontal edge exceeds the maximum usage allowed.");
Horizontal edge usage exceeds the maximum allowed

2021-06-26 03:11 UTC, maliberty commented on src/grt/src/fastroute/src/utility.cpp
> +  int max_h_edge_usage = 40 * hCapacity;
Make 40 into a named constant that is shared by both pieces of code.

2021-06-26 14:15 UTC, eder-matheus commented
> Why are we allowing routing to end with overflow by default? We will be passing an infeasible solution onto detailed routing which will likely fail too.

You're right, I think I made confusion here. I will update my code to allow overflow during the routing process (removing the `allowOverflow` flag from the core code), but I'll keep the check after the routing is complete. Therefore, I'll restore the `-allo_overflow` option (and probably change it to `-allow_congestion`.

2021-06-28 20:48 UTC, eder-matheus commented
@maliberty any further comments/requests?

2021-06-28 21:11 UTC, maliberty approved these changes

2021-06-28 21:13 UTC, merged